### ISSUE TITLE
URI keywords shouldn't include header params

### ISSUE THREAD

**Issue by rkday** [SIPp/sipp#10]
SIPped, the Polycom fork of SIPp (https://github.com/SIPp/polycom-sipped) fixes up the keyword generation, so that keywords like [next_uri] include only the URI and not any header parameters on the end. It would be good to get this merged into the main SIPp code.

It looks as though the relevant commit is 57220e0.

**Comment by wdoekes** [comment]
AFAIK Contact parsing has been fixed in 498b965a17 and Record-Route parsing in b6c7b20977.
