### ISSUE TITLE
Decide whether to leave autogenerated files in the git repo.

### ISSUE THREAD

**Issue by wdoekes** [SIPp/sipp#112]
In #110 @vodik and @lemenkov prefer to remove autogenerated files:

> Great! Now what about killing autogenerated files? I personally see no reason for keeping them, and they are the constant source of git noise if you run autoreconf.

I personally don't see them as a constant source of noise, as there are relatively few changes to autoconf, in general.

Advantages to removing them:
- less noise;
- no redundant (large) data in the repository.

Disadvantages:
- more and more people use git checkouts instead of tgz downloads. They expect to be able to `./configure` and `make` without hassle. If we remove the autogenerated files, we force users to install more (auto)tools.

**Comment by Lekensteyn** [comment]
Auto-generated files do not belong to a git repo and requiring `build.sh` to touch Makefiles and such shows that it is an unreliable hack. Vote for removal of auto-generated files!
