### ISSUE TITLE
Access to field 'size' results in a dereference of a null pointer (loaded from variable 'userVars')

### ISSUE THREAD

**Issue by vodik** [SIPp/sipp#116]
> Bug reported by the clang static analyzer.
>
> Description: Access to field 'size' results in a dereference of a null pointer (loaded from variable 'userVars')
> File: /home/simon/code/vodik/sipp/src/call.cpp
> Line: 559

Basically if at line 547 `it == userVarMap.end()`, we end up with `userVars` being NULL:

```c
int_vt_map::iterator it = userVarMap.find(userId);
if (it != userVarMap.end()) {
    userVars = it->second;
}
```

So later on this branch will result in a null derefence error:

```c
...
} else if (userVars->size > 0) {
    M_callVariableTable = userVars->getTable();
} else if (globalVariables->size > 0) {
...
```

Wasn't sure what the right logic should be if the find fails. Bail or create a new variable table?

**Comment by wdoekes** [comment]
Not sure whether an `assert(userVars)` would've been fine too, but adding a `userVars!=NULL` check seems safe enough for this case.
