### ISSUE TITLE
What is the etymology of SIPp?

### ISSUE THREAD

**Issue by mx4492** [SIPp/sipp#122]
Just curious. I could not find any mailing list thread that explains why this name came around. Is it an acronym? 

The closest answer I found was that SIPp stands (or stood) for "SIP protocol". I base that on the contents of the header in the `README.txt` from the original [SVN source](http://svn.code.sf.net/p/sipp/code/sipp/trunk/README.txt):

```
#   SIPp - a SIP protocol test tool
...
```

**Comment by wdoekes** [comment]
My best guess would be "SIP performance", but that's just based on documents that refer to the use of SIPp for performance testing.

Note that in 2006, it was called "Sipp" -- not "SIPp" -- in the README:

    $ git show 3d805744e39370c7a31c1d04e815551810da2dba:README.txt | grep package
    This is the Sipp package. Please refer to the http://sipp.sourceforge.net/
