### ISSUE TITLE
SIPP ignoring optional tag

### ISSUE THREAD

**Issue by antonmry** [SIPp/sipp#127]
Hello,

I am using this scenario: http://pastebin.centos.org/25806/ but when I executed it, I've received this error:

```
2015-04-20      18:54:49:319    1429548889.319000: Aborting call on unexpected message for Call-Id '1-7107@172.31.25.100': while expecting '100' (index 1), received 'SIP/2.0 200 OK
```

It's ignoring **optional** here:

```
  <recv response="100" optional="true"> </recv>
```

I've tested versions:
* SIPp v3.3-TLS-SCTP-PCAP, built Feb 15 2013, 06:11:36.
* SIPp v3.4.1-RTPSTREAM built Apr 20 2015, 18:39:10

I know the scenario is working with an old sipp file. Has  this tag changed in the last versions?

**Comment by wdoekes** [comment]
Your scenario specifies that the 401 is not optional: looks to me like you didn't get a 401 but a straight 200. In that case you'll get the above error.

**Comment by antonmry** [comment]
Walter, you are right. I was confused because of the error message (expecting 100 instead of expecting 401). Thanks for your help.
