### ISSUE TITLE
Rename `callid_slash` command line option

### ISSUE THREAD

**Issue by wdoekes** [SIPp/sipp#135]
Rob, in 7c7a5a1b, you added the `-callid_slash` option.

I don't think the option name covers its behaviour; it doesn't add a slash, it undoes special behaviour.

Can we change that? Perhaps to `-no_callid_magic` or something?

**Comment by rkday** [comment]
Yes, sorry - I'd seen your comment but not got round to applying it. See #136?

**Comment by wdoekes** [comment]
Thanks :)
