### ISSUE TITLE
Decide on a c/c++ standard to target.

### ISSUE THREAD

**Issue by vodik** [SIPp/sipp#139]
There's a lot of c/c++ code I'd like to cleanup but I need to know what standard I can target. Currently when building sipp with lots of warnings about stuff that either c++11 or gnu extensions (eg: `-Wc++11-long-long`, `-Wc++11-extra-semi`, `-Wc++11-extensions`).

One of the things I'd like to consider is trying to port stuff to smart pointers wherever possible and c++11 helps that.

**Comment by vodik** [comment]
Well, for what its worth, compiles just fine on GCC, which for the C code means we default to gnu11

**Comment by wdoekes** [comment]
I don't have an opinion about which standard to target. The docs read that it should be compilable on Mac OSX, FreeBSD, Linux and Cygwin.

Personally I'm fine with any suggested standard. I'd rather see native Windows compilation over Cygwin though. (There's a ticket for that: #23.) Something to keep in mind.

@lemenkov @rkday poke

**Comment by lemenkov** [comment]
@vodik I like C++11 idea. if you asked me I'd say I have a go.
@rkday what's your opinion on that matter?

**Comment by vodik** [comment]
@wdoekes MSCV has excellent c++11 support. I'm mainly concerned with whether `std::unique_ptr` is kosher or not.

**Comment by vodik** [comment]
Okay, I snuck this in to make the decision easier, feel free to reject it.

**Comment by rkday** [comment]
I'm happy with C++11 - I'd like SIPp to still be available on RHEL6/CentOS 6, but I think that's fine (GCC 4.7 is available for those according to http://superuser.com/questions/381160/how-to-install-gcc-4-7-x-4-8-x-on-centos) - and even if there are problems, I think it's OK to document 'version Y is the last one supported on RHEL6'.

@vodik, if you raise a PR with your commit 5a21956, I think there's sufficient consensus to merge it.

**Comment by rkday** [comment]
(Ah, didn't spot that it's in https://github.com/SIPp/sipp/pull/140/files - still catching up after a holiday.)
