### ISSUE TITLE
EAFNOSUPPORT on ipv6 regression

### ISSUE THREAD

**Issue by vodik** [SIPp/sipp#150]
The following command causes `EAFNOSUPPORT` errors in `./sipp -sn uac '[::1]:12347' -p 12348`. Looking at an strace, looks like:

``` strace
socket(PF_INET, SOCK_DGRAM, IPPROTO_UDP) = 4
bind(4, {sa_family=AF_INET, sin_port=htons(12348), sin_addr=inet_addr("0.0.0.0")}, 16) = 0
sendto(4, "INVITE sip:service@[::1]:12347 S"..., 512, 0, {sa_family=AF_INET6, sin6_port=htons(12347), inet_pton(AF_INET6, "::1", &sin6_addr), sin6_flowinfo=0, sin6_scope_id=0}, 28) = -1 EAFNOSUPPORT (Address family not supported by protocol)
```

**Comment by vodik** [comment]
And there's no obvious reason why I see it working at 9b39e59accbad9193a6f2bdd55d02c5f0a0e730f but failing on 6aec4e8f2cfdf02498d48d7dc0d1a982845016ec... especially considering how trivial that patch is.

**Comment by vodik** [comment]
Okay, debugging this, looks like the logic for setting `local_ip_is_ipv6` is bypassed for some reason and we never detect it correctly.

**Comment by vodik** [comment]
Actually, looks like `open_connections` can fill the local address information with an IPv4 address even if we're connecting to a remote host.

**Comment by vodik** [comment]
Okay, looks like the fix is simple:

1. We should use the remote socket's family when trying to determine a local sockaddr.
2. Replace the `gethostname(hostname, 64)` with a straight `"localhost'` as a fallback instead.

I need to look into this a little deeper... looks like there are some really weird assumptions in here though. I'll get a patch up later night hopefully.

@rkday how's your branch coming along? If I dive into this, I'd rather not redo the good work you're doing.

**Comment by wdoekes** [comment]
Thanks for looking into this. I added a quick regression test.

**Comment by rkday** [comment]
I've updated https://github.com/SIPp/sipp/pull/148 with my latest code. I'm not sure about replacing `gethostname(hostname, 64)` with `localhost` as a fallback, though - in my /etc/hosts (Fedora 20), localhost is 127.0.0.1 and localhost6 is `::1`, so `localhost` would never resolve to an IPv6 address.

I wonder if the right approach here is to be explicit about what local IP we're choosing if it isn't set on the command line, and maybe warning if the local and remote IP address families don't match, so the user can spot the mistake and choose the right one explicitly.

**Comment by wdoekes** [comment]
Beware, I just force-pushed over my regression test. After fixing it, it's now happy with patch #151.

**Comment by vodik** [comment]
@rkday `localhost` should resolve to both, they've just additionally added `localhost4` and `localhost6`. If they aren't doing that, they're breaking software for sure (just checked a CentOS box).

> explicit about what local IP we're choosing if it isn't set on the command line, and maybe warning if the local and remote IP address families don't match, so the user can spot the mistake and choose the right one explicitly.

Well, the first part of the fix is enough to cover this. The issue was that it resolved the remote ip (::1) correctly, but then resolves my hostname for ipv4 even though there's a ipv6 record. The correct thing is to look for the same address family as the remote and bail if a match can't be found.

This came up only because of a regression on `nss_myhostname`. It was working fine... then started reporting the link-local address of the wrong interface for my hostname (which is why it started reporting the v4 address in the first place, getaddrinfo lists link-local last).

This broke whatever socket operations it was doing. I'm not super familiar with the code but I have a suspicion `open_connections` is establishing all sorts of sockets, even ones it doesn't use.

Technically we might have the same problem the problem potentially in reverse, but the Linux kernel can tunnel v4 over v6 internally (don't know about other platforms).

As far as what `hostname` resolves to, my understanding is it can be either loopback address or an external interface in practice. Basically the only assumption is that it points back to the machine, I don't think it can be used safely as a source address we bind to.
