### ISSUE TITLE
Epollevents as vector breaks basic functionality

### ISSUE THREAD

**Issue by wdoekes** [SIPp/sipp#155]
```
commit 17ad0610ef35607b50bfba51c85ac63c062eb731
Author: Simon Gomizelj <sgomizelj@sangoma.com>
Date:   Tue Jun 16 18:44:32 2015 -0400

    Convert epollevents to a vector
```

Example:
```
$ ./sipp -sn uas -m 10 -p 5070
$ ./sipp -m 10 -sn uac 127.0.0.1:5070
```

Yields: 0 received packets in uas.

**Comment by wdoekes** [comment]
@vodik, I reverted 17ad0610 in 40a184fb.

**Comment by vodik** [comment]
:disappointed: shit, sorry.

**Comment by moises-silva** [comment]
@vodik from a glance at the original commit, only the extern declaration was redefined to vector, the actual definition in socket.cpp was left as struct epoll_event *epollevents. Can't tell if that's the reason it does not work though ...

**Comment by vodik** [comment]
Yeah its a mess.

**Comment by vodik** [comment]
I'm going to close this for now.
