### ISSUE TITLE
VLAN, SLL and radiotap support in prepare_pcap

### ISSUE THREAD

**Issue by rkday** [SIPp/sipp#16]
SIPped, the Polycom fork of SIPp (https://github.com/SIPp/polycom-sipped) enhances PCAP playback support so that other packet formats can be used. It would be good to get this merged into the main SIPp code.

It looks as though the relevant commits are 3a78580, a884b18, bbdd6c3, a95567a, 02d5fab, 5545172, 64b34aa and 9d66ded.

**Comment by hpaskalev** [comment]
Check out my pull request -  #161. I've got something for VLANs as I recently stumbled upon a pcap that wasn't playable.
