### ISSUE TITLE
pcap play sends traffic to the port 0

### ISSUE THREAD

**Issue by vodik** [SIPp/sipp#163]
Our internal sipp fork, based around 3.2, works correctly: ![good][]

The upstream version doesn't. Seems like this problem has been in the codebase for a while, testing the 3.5-rc1 tag directly has the same flaw.
![bad][]

  [good]: https://cloud.githubusercontent.com/assets/216803/8660849/67b874de-2981-11e5-996f-829cb0fd98e9.png
  [bad]: https://cloud.githubusercontent.com/assets/216803/8660848/64b1a152-2981-11e5-8d5a-a9a147571099.png

Note the 3rd rtp stream.

@wdoekes This is one of the main reasons for the revert. I didn't want to have to struggle with bugs I introduce when sipp seems to have some already :wink:.

**Comment by vodik** [comment]
Seems like a regression introduced in 0026639e7c2f9c3e10536ee86d0508e699e0cd70.

**Comment by wdoekes** [comment]
Ouch. Thanks for fixing that as well :)
