### ISSUE TITLE
Docs are unavailable (sourceforge is down)

### ISSUE THREAD

**Issue by aphistic** [SIPp/sipp#165]
Would it be possible to move the docs site over to the github project pages? As far as I can tell development has been moved over to github but the main site is still over on sourceforge, which has been down for a number of days now.  I realize moving from sourceforge to github is still a single point of failure, but it seems like github is more stable than sourceforge these days.

Is there anything I could do to help with the transition if it's possible?

**Comment by vodik** [comment]
@rkday started doing them up here: http://sipp.readthedocs.org/en/latest/ (see https://github.com/SIPp/sipp/pull/141#issuecomment-106930937), I started toying with using gh_pages on my fork before I learned about the readthedocs effort.

**Comment by wdoekes** [comment]
Closed in favor of #226 .
