### ISSUE TITLE
Possible copy and paste error

### ISSUE THREAD

**Issue by vodik** [SIPp/sipp#172]
Caught by Coverity, but I'm not familiar enough with the functionality to know for sure if its a bug. In rtpstream:

~~~c
    if (taskinfo->video_rtp_socket != -1) {
        /* just keep listening on rtp socket (is this really required?) - ignore any errors */
        while ((rc = recv(taskinfo->video_rtcp_socket, udp.buffer, sizeof(udp), 0)) >= 0) {
            /*
             * rtpstream_bytes_in += rc;
             */
        }
    }
~~~

I get:

>     CID 130068 (#1 of 1): Copy-paste error (COPY_PASTE_ERROR)copy_paste_error: video_rtcp_socket in taskinfo->video_rtcp_socket looks like a copy-paste error.
 >     Should it say video_rtp_socket instead?

**Comment by wdoekes** [comment]
From a cursory glance, line 300 looks wrong too:
https://github.com/SIPp/sipp/blob/bf6bccb1a5005ac86f8b779c257b912dec2c74ef/src/rtpstream.cpp#L300

It looks sane in the initial revision:
```$ git show 78a2514ec0bfdb64ba94fbfb8adf8b41e1e511fa
...
+  if (taskinfo->audio_rtcp_socket!=-1) {^M
+    /* just keep listening on rtcp socket (is this really required?) - ignore any errors */^M
+    while ((rc= recv (taskinfo->audio_rtcp_socket,udp_buffer,sizeof(udp_buffer),0))>=0) {^M
...
+  if (taskinfo->video_rtp_socket!=-1) {^M
+    /* just keep listening on rtp socket (is this really required?) - ignore any errors */^M
+    while ((rc= recv (taskinfo->video_rtp_socket,udp_buffer,sizeof(udp_buffer),0))>=0) {^M
...
+  if (taskinfo->video_rtcp_socket!=-1) {^M
+    /* just keep listening on rtcp socket (is this really required?) - ignore any errors */^M
+    while ((rc= recv (taskinfo->video_rtcp_socket,udp_buffer,sizeof(udp_buffer),0))>=0) {^M
...
+  if (taskinfo->audio_rtp_socket!=-1) {^M
+    /* this is temp code - will have to reorganize if/when we include echo functionality */^M
+    /* just keep listening on rtcp socket (is this really required?) - ignore any errors */^M
+    while ((rc= recv (taskinfo->audio_rtp_socket,udp_buffer,sizeof(udp_buffer),0))>=0) {^M
```
I.e. we recv on the socket that we just checked in the if.

After browsing some more, I'm afraid you altered it in 901f1c27a25a86ca28358cf019f342895e605dff.

So yes, it's a bug. Thanks for finding that :)

**Comment by vodik** [comment]
Aww shit, well then, I'll fix it.

**Comment by vodik** [comment]
By the way, give me heads up if you want access to the sipp Coverity page.

**Comment by wdoekes** [comment]
I'm an avid collector of access ;)

**Comment by vodik** [comment]
I just need an email address as far as I know. Feel free to email me it since I assume you're intentionally not sharing it.
