### ISSUE TITLE
Why didn't IMSBench SIPp update the latest version of SIPp on it?

### ISSUE THREAD

**Issue by hiepnm** [SIPp/sipp#179]
I have a task for benchmarking an IMS system. And I found a tools that is IMSBench SIPp (http://sipp.sourceforge.net/ims_bench/intro.html). But, SIPp version on this tool is 1.1, when the latest version of stable SIPp is 3.4.

**Comment by wdoekes** [comment]
I don't have access to SF. And I don't know exactly what you want. Please re-open with more info if this is still an issue.
