### ISSUE TITLE
[date] keyword failure

### ISSUE THREAD

**Issue by mMontu** [SIPp/sipp#180]
I found a case where it would be useful to insert the current timestamp on a log message, and then I happily discovered that this is already possible on SIPp. From http://sourceforge.net/p/sipp/mailman/message/32880674/:

> ...
> Re: [Sipp-users] support for date & timestamp headers
> From: Rob Day <rkd@rk...> - 2014-09-29 22:20:13
> Attachments: uac_date.xml    
> ...
> SIPp 3.4.1 had no support for the date, but it looks like a useful
> feature, so I've just added it to the codebase at
> https://github.com/SIPp/sipp. The [date] keyword should now do what
> you want.
> 
> The attached script produces the following INVITE for me:
> ...

But running the xml attached on that message fails with the following error:

    2015-11-24      08:07:00.627359 1448370420.627359: Unsupported keyword 'date' in xml scenario file.

(SIPp on ba0c8c2) 
Do you have any ideas?

**Comment by wdoekes** [comment]
That's odd.

I tried this:
```
--- a/regress/github-#0085/uac.xml
+++ b/regress/github-#0085/uac.xml
@@ -10,6 +10,7 @@
       To: [service] <sip:[service]@[remote_ip]:[remote_port]>
       Call-ID: [call_id]
       CSeq: 1 INVITE
+      Date: [date]
       Contact: sip:sipp@[local_ip]:[local_port]
       Max-Forwards: 70
       Content-Type: application/sdp
```

And:

```
$ ./sipp -m 1 -sf ./regress/github-#0085/uac.xml 1.2.3.4 -trace_msg
^C
```

Which yields the following in the log:

```
INVITE sip:service@1.2.3.4:5060 SIP/2.0
Via: SIP/2.0/UDP 127.0.1.1:5060;branch=z9hG4bK-14539-1-0
From: sipp <sip:sipp@127.0.1.1:5060>;tag=14539SIPpTag001
To: service <sip:service@1.2.3.4:5060>
Call-ID: 1-14539@127.0.1.1
CSeq: 1 INVITE
Date: Wed, 20 Jan 2016 21:07:35 GMT
Contact: sip:sipp@127.0.1.1:5060
Max-Forwards: 70
Content-Type: application/sdp
Content-Length:   129
```

A valid date, as far as I can tell.

Are you sure you're running the SIPp version you say you're running? Or are you doing something different with your scenario?

**Comment by mMontu** [comment]
> Are you sure you're running the SIPp version you say you're running? Or are you doing something different with your scenario?

This is indeed the problem -- I was using a far older version: f4699d9

Thanks!
