### ISSUE TITLE
Docmentation for Sipp Code

### ISSUE THREAD

**Issue by usman092** [SIPp/sipp#181]
There should be a documentation for Sipp code, so a new developer can easily make changes if he wants to.

**Comment by wdoekes** [comment]
Hi Usman,

more documentation is indeed better. But as it stands, this is just one of many things that would improve the project, and this is not one that I think one of the current maintainers will pick up on.

If you have a starting point of such documentation, we'll gladly look at a pull request. Thanks! :)
