### ISSUE TITLE
Integrating python backed unit testing

### ISSUE THREAD

**Issue by tgoodlet** [SIPp/sipp#188]
Hey guys,

I recently wrapped up the first version of a python launcher for SIPp, [pysipp](https://github.com/tgoodlet/pysipp), which we're using over at [sangoma](https://github.com/sangoma) for functional testing of FreeSWITCH and other products.

We pair it with [pytest](http://pytest.org/latest/) which is probably the most powerful and flexible python test framework. It's got a lot of features focusing on [DDT](https://en.wikipedia.org/wiki/Data-driven_testing) which might be handy considering SIPp's interface. I was thinking it might serve as a better alternative for unit testing then the ruby tool suggested in the backlogged #4.

Anyway, if you guys are interested I'd be happy to move the repo over here.

**Comment by wdoekes** [comment]
Well. I'd love to get a standardized feature-rich python interface to SIPp.

If I recall correctly, @vodik suggested to incorporate it earlier. I remember not being enthusiastic then, but I may have changed my opinion. I use custom python sipp calling conjoined into the Django test suite with a few of my clients, but it's not ready for publication at all (imo).

Unfortunately I don't have the time right now to examine the features of pysipp, but if you and @vodik are happy users, I wouldn't mind seeing it here. But, I don't have admin powers on this organisation. Poking @rkday.

As for #4, that is probably not be on @rkday's priority list anymore, as he seemed to be working on a SIPp replacement in ruby directly. https://github.com/rkday/quaff

**Comment by rkday** [comment]
@wdoekes - I've given you admin powers over the SIPp organisation, so you should be able to do whatever you like - ping me again if it hasn't worked.

**Comment by tgoodlet** [comment]
@wdoekes So what do you think? Should we move it over here?

**Comment by wdoekes** [comment]
Hi, sorry for the delay. I'll take a look at your project this weekend and decide :)

**Comment by tgoodlet** [comment]
@wdoekes Great. If you have anything you want changed/improved I'm happy to get it there.
Documentation is pretty lacking so if you have any questions my freenode handle is *goodboy*.

**Comment by wdoekes** [comment]
So I took it for a tiny spin.

After figuring out how to add my common arguments, it did its magic like it's supposed to:

    uac = pysipp.client(destaddr=('myserver', 5060))
    uac.uri_username = '123'
    uac.auth_password = '123'
    uac.scen_file = 'my.xml'
    uac()

I'd have to see how well it works with the ipc_host and my transfer scenario's to see if it can replace my current setup. That's for another day. As far as I can tell it looks promising and the code certainly looks good enough.

I've forked your repo into the SIPp organisation and added you as committer to the committers team. So you should have full access to it.

Let me know if something is missing.

**Comment by tgoodlet** [comment]
@wdoekes Great!
I was actually thinking I'd just [transfer the repo](https://help.github.com/articles/transferring-a-repository/) to this organization unless you'd rather keep just a fork here (which is cool too).
Let me know.

**Comment by wdoekes** [comment]
Ah. Sure thing.

Fork removed...

**Comment by wdoekes** [comment]
Click, click, triple-click. I think you have pysipp admin powers now.

**Comment by tgoodlet** [comment]
@wdoekes So I tried to transfer it but got an error saying "The repo SIPp/pysipp already exists". When I looked at the org's main page there was an empty `pysipp` repo there. So I deleted it in an attempt to avoid the problem and now when I try to transfer github is telling me "You don’t have admin rights to SIPp". Looks like you'll have to set me up as a temporary admin [according to this](https://help.github.com/articles/transferring-a-repository/#transferring-from-a-user-to-an-organization).

**Comment by wdoekes** [comment]
Well, I tried. But like this morning, I cannot figure out how I'm suppose to hand out admin powers without a repository. So, now you're a temporary owner instead :P 

I'll fix your admin perms when you've moved the repo.

**Comment by tgoodlet** [comment]
@wdoekes Done. You can revoke my temp admin access if you want.

**Comment by wdoekes** [comment]
Awesome! You've been de-ownered and are now admin of pysipp.

(And I think I found the flag: in the organisation settings there is an option that allows "plain" Members to create new repositories. Next time, I'll tick that box instead.)

**Comment by wdoekes** [comment]
If there was ever a moment to plug pysipp, here's your chance ;)
https://sourceforge.net/p/sipp/mailman/message/34904512/
