### ISSUE TITLE
Wrong qop escaping (v.3.5.0)

### ISSUE THREAD

**Issue by artlov** [SIPp/sipp#191]
After upgrade to the version 3.5.0 registration broken with error code:
_SIP/2.0 400 Bad header field: authorization_
Reason is in the qop wrong escaping. Regarding RFC3261 Instead of _qop="auth"_ it should be _qop=auth_:
>    An example of the Authorization header field is:
      Authorization: Digest username="bob",
              realm="biloxi.com",
              nonce="dcd98b7102dd2f0e8b11d0f600bfb0c093",
              uri="sip:bob@biloxi.com",
              qop=auth,
              nc=00000001,
              cnonce="0a4f113b",
              response="6629fae49393a05397450978507c4ef1",
              opaque="5ccc069c403ebaf9f0171e9517f40e41"

Small patching helped me out:
```
diff -Nur a/src/auth.cpp b/src/auth.cpp
--- a/src/auth.cpp	2016-02-08 23:58:43.000000000 +0200
+++ b/src/auth.cpp	2016-02-17 12:42:51.000000000 +0200
@@ -372,7 +372,7 @@
     }
 
     if (cnonce[0] != '\0') {
-        snprintf(tmp, sizeof(tmp), ",cnonce=\"%s\",nc=%s,qop=\"%s\"", cnonce, nc, authtype);
+        snprintf(tmp, sizeof(tmp), ",cnonce=\"%s\",nc=%s,qop=%s", cnonce, nc, authtype);
         strcat(result, tmp);
     }
     snprintf(tmp, sizeof(tmp), ",uri=\"%s\"", sipuri);
```

**Comment by wdoekes** [comment]
Thank you for the bug report!

You are absolutely right, and I'm working on a fix.
