### ISSUE TITLE
Unable to compile under Cygwin

### ISSUE THREAD

**Issue by Gankarloo** [SIPp/sipp#193]
I get the following error when trying to compile. 
Any ideas? 

```
src/socket.cpp: In function ‘void reset_stdin()’:
src/socket.cpp:549:21: error: ‘fileno’ was not declared in this scope
   fcntl(fileno(stdin), F_SETFL, stdin_mode);
                     ^
src/socket.cpp: In function ‘void setup_stdin_socket()’:
src/socket.cpp:554:36: error: ‘fileno’ was not declared in this scope
     stdin_mode = fcntl(fileno(stdin), F_GETFL);
                                    ^
makefile:1632: recipe for target 'src/sipp-socket.o' failed
gmake: *** [src/sipp-socket.o] Error 1

```

**Comment by wdoekes** [comment]
Does this help:

https://github.com/SIPp/sipp/commits/fix/add-missing-stdio-193

**Comment by Gankarloo** [comment]
Sorry it does not.
I still get the same error only on line 550 and 555 due to the extra line in your fix.

Is there any more info I could provide?

**Comment by wdoekes** [comment]
And what does this do:

    make CXXFLAGS="-std=gnu++11"

**Comment by Gankarloo** [comment]
Yes that did the trick,
Thanks a lot

2016-03-03 22:04 GMT+01:00 Walter Doekes <notifications@github.com>:

> And what does this do:
>
> make CXXFLAGS="-std=gnu++11"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/SIPp/sipp/issues/193#issuecomment-191961931>.
>



-- 
MVH
Gustaf Ankarloo
0723-232344
