### ISSUE TITLE
SIPp build fails on Cygwin

### ISSUE THREAD

**Issue by timothyarm** [SIPp/sipp#194]
Seems like a configured build with a pretty standard Cygwin64 build fails.

g++ -DHAVE_CONFIG_H   -DRTP_STREAM    -I. -I./include   -D__CYGWIN -I /usr/include/ncurses -I /usr/lib/WpdPack/Include -I /usr/include/SctpDrv -I./include -Wall -pedantic  -g -O2 -std=c++11 -MT src/sipp-socket.o -MD -MP -MF src/.deps/sipp-socket.Tpo -c -o src/sipp-socket.o `test -f 'src/socket.cpp' || echo './'`src/socket.cpp
src/socket.cpp: In function ‘void reset_stdin()’:
src/socket.cpp:549:21: **error: ‘fileno’ was not declared in this scope
   fcntl(fileno(stdin), F_SETFL, stdin_mode);**
                     ^
src/socket.cpp: In function ‘void setup_stdin_socket()’:
**src/socket.cpp:554:36: error: ‘fileno’ was not declared in this scope
     stdin_mode = fcntl(fileno(stdin), F_GETFL);**
                                    ^
Makefile:1632: recipe for target 'src/sipp-socket.o' failed

Looking at some [StackOverflow ](https://stackoverflow.com/questions/18784112/googletest-1-6-with-cygwin-1-7-compile-error-fileno-was-not-declared-in-this) [answers](https://stackoverflow.com/questions/15944051/error-fdopen-was-not-declared-found-with-g-4-that-compiled-with-g3), it seemed like std=c++11 was the issue. **I tried building with std=gnu++11 which succeeded.**

I can provide additional information on request.

**Comment by lemenkov** [comment]
@wdoekes @rkday btw we should try setting up a CI for Windows targets. There are some services available (some of them are free for open source apps, such as [AppVeyor](http://www.appveyor.com/)).

**Comment by wdoekes** [comment]
@lemenkov: if you file a PR, I'll gladly look at it :)

@timothyarm: thank you for the bug report! Did you happen to see #193 which was fixed by 44619c6 just the other day? I believe that fixes your issue.

**Comment by timothyarm** [comment]
Looks like #193 is exactly the same...I've got a lot to learn about this stuff.
