### ISSUE TITLE
Getting error after running ./build.sh --full 

### ISSUE THREAD

**Issue by srthorat** [SIPp/sipp#197]
root@mail1:~/test/sipp-master# ./build.sh -full
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --force-missing
autoreconf: Leaving directory `.'
configure: error: unrecognized option: `-full'
Try `./configure --help' for more information
root@mail1:~/test/sipp-master#
root@mail1:~/test/sipp-master#
root@mail1:~/test/sipp-master#
root@mail1:~/test/sipp-master# ./build.sh --full
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /usr/bin/autoconf --force
autoreconf: running: /usr/bin/autoheader --force
autoreconf: running: automake --add-missing --force-missing
autoreconf: Leaving directory `.'
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for help2man... no
configure: WARNING: cannot find help2man, you will not be able to generate manpages
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking whether g++ supports C++11 features by default... no
checking whether g++ supports C++11 features with -std=gnu++11... yes
checking whether C compiler accepts -std=gnu11... yes
checking for initscr in -lcurses... yes
checking for pthread_mutex_init in -lpthread... yes
checking for library containing dlopen... -ldl
checking for library containing dlerror... none required
checking for library containing dlsym... none required
checking for library containing clock_gettime... none required
checking for library containing inet_addr... none required
checking for library containing inet_ntoa... none required
checking for library containing pthread_mutex_init... none required
checking for library containing pthread_mutex_destroy... none required
checking for library containing pthread_mutex_lock... none required
checking for library containing pthread_mutex_unlock... none required
checking for library containing pthread_self... none required
checking for library containing pthread_cancel... -lpthread
checking for library containing pthread_join... none required
checking for library containing pthread_attr_init... none required
checking for library containing pthread_attr_setstacksize... none required
checking for library containing pthread_create... none required
checking for library containing pthread_attr_destroy... none required
checking for library containing pthread_setschedparam... none required
checking for library containing pthread_setcancelstate... none required
checking for library containing pthread_setcanceltype... none required
checking for library containing pthread_exit... none required
checking for library containing pthread_sigmask... none required
checking for library containing floor... -lm
checking for library containing pow... none required
checking for library containing htons... none required
checking for library containing ntohs... none required
checking for library containing bind... none required
checking for library containing freeaddrinfo... none required
checking for library containing getaddrinfo... none required
checking for library containing listen... none required
checking for library containing recvfrom... none required
checking for library containing shutdown... none required
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking openssl/md5.h usability... yes
checking openssl/md5.h presence... yes
checking for openssl/md5.h... yes
checking openssl/bio.h usability... yes
checking openssl/bio.h presence... yes
checking for openssl/bio.h... yes
checking openssl/err.h usability... yes
checking openssl/err.h presence... yes
checking for openssl/err.h... yes
checking openssl/rand.h usability... yes
checking openssl/rand.h presence... yes
checking for openssl/rand.h... yes
checking openssl/ssl.h usability... yes
checking openssl/ssl.h presence... yes
checking for openssl/ssl.h... yes
checking openssl/x509v3.h usability... yes
checking openssl/x509v3.h presence... yes
checking for openssl/x509v3.h... yes
checking for SSL_library_init in -lssl... yes
checking for CRYPTO_num_locks in -lcrypto... yes
checking netinet/sctp.h usability... yes
checking netinet/sctp.h presence... yes
checking for netinet/sctp.h... yes
checking for library containing sctp_send... -lsctp
checking for library containing sctp_freepaddrs... none required
checking for library containing sctp_bindx... none required
checking for library containing sctp_recvmsg... none required
checking pcap.h usability... yes
checking pcap.h presence... yes
checking for pcap.h... yes
checking for library containing pcap_open_offline... -lpcap
checking for library containing pcap_next... none required
checking for library containing pcap_close... none required
checking for pcap_next_ex in -lpcap... yes
checking gsl/gsl_randist.h usability... no
checking gsl/gsl_randist.h presence... no
checking for gsl/gsl_randist.h... no
configure: error: <gsl/gsl_randist.h> header missing

**Comment by srthorat** [comment]
missed lasted line to paste

configure: error: <gsl/gsl_randist.h> header missing

**Comment by wdoekes** [comment]
I believe you don't have the gsl devel package installed.

Have you tried `./build.sh` without `--full` ? That would create a build without all the extra dependencies and should succeed.

Alternately you can supply individual `--with-...` flags, see the README and ./configure --help.

Or you can install the gsl devel package (libgsl0-dev on debian/ubuntu).

**Comment by wdoekes** [comment]
In fact, you can peek here what the automated build uses:
https://github.com/SIPp/sipp/blob/master/.travis.yml#L13
https://github.com/SIPp/sipp/blob/master/.travis.yml#L18
That should help you get started.

**Comment by wdoekes** [comment]
I guess you've succeded by now. Let me just close this out.

**Comment by srthorat** [comment]
still getting 

root@mail1:~/test/sipp-master# make
make: *** No rule to make target `include/version.h', needed by `src/call.cpp'.  Stop.

**Comment by wdoekes** [comment]
I don't know what you did, but it should generate the include/version.h automatically.

    rm .version

and try `make` again.

**Comment by srthorat** [comment]
i dnt knw what was wrong but able compile latest release sipp-3.5.1

**Comment by wdoekes** [comment]
Good.

I bet there was something wrong with your git checkout. Glad it works now.
