### ISSUE TITLE
Way to gracefully stop sipp when in the background

### ISSUE THREAD

**Issue by atsakiridis** [SIPp/sipp#210]
Imagine that you want to start a nightly test in amazon EC2 so you start sipp with nohup and the terminal times out at some point. When you login again next morning there is no way to `fg` it as sipp doesn't exist as a background job in any terminal. So I guess the best way to signal it is through, well signal.

From the code I saw that you already have some handling for SIGALRM but I tried it and seems like the execution is somehow pause. Is there a way to signal the sipp process to gracefully stop? If not I could contribute a fix to that with some guidance, as I think it is a very handy feature.

What do you think

Best regards,
Antonis Tsakiridis

**Comment by vodik** [comment]
Sorry for the long delay. Try `SIGUSR1`. Its supposed to be a smooth exit.

**Comment by atsakiridis** [comment]
Great thanks
