### ISSUE TITLE
sipp 3.5.1 won't compile with `--with-pcap`

### ISSUE THREAD

**Issue by mscdex** [SIPp/sipp#211]
Evidently `include/endianshim.h` isn't complete enough. I found that replacing the existing file with the contents of [this file](https://sourceforge.net/p/cap2hccap/svn/2/tree/trunk/include/byteorder.h) allows compilation to succeed.

FWIW I was compiling on CentOS 5 with devtoolset-2 (gcc/g++ 4.8.2).

**Comment by wdoekes** [comment]
Hi there, thanks for you bug report and proposed fix.

However, you will agree with me here that blindly including a big chunk of source -- with unrelated additional defines -- just because it works in your case may not be the most appropriate fix.

Could you describe which error(s) you get?

**Comment by mscdex** [comment]
`le16toh` was undefined. I just mentioned/"suggested" that source file since it seemed to be more complete than the existing shim. Ultimately it's up to you though \*shrug\*.

**Comment by wdoekes** [comment]
Thanks.

Note to self:
https://gist.github.com/panzi/6856583#gistcomment-1656524
_BSD_SOURCE is already defined on own platform so simply including it before endian.h causes conflicts.

**Comment by wdoekes** [comment]
Does this work for you: https://github.com/SIPp/sipp/compare/fix/3.5/missing-le16toh-on-centos5-211 ?

**Comment by mscdex** [comment]
I'm not able to use `autoconf` to build from the repo because it's too old, but applying 15af1fcc13c195ad380e187875195e1b02017495 to the same 3.5.1 release tarball results in the same error as before.

**Comment by wdoekes** [comment]
I added a new fix. I'm pretty sure this should work, but if you could confirm, that would be great.

Without git and autoconf, I guess you'd have to patch this:
https://github.com/SIPp/sipp/commit/03d656652776e0e292f1d890ffdff2898df6adc5.patch
And run this:
http://junk.devs.nu/configure (md5sum 056d2705e9b0b69ec8c0bdeacbe98f36)
