### ISSUE TITLE
RTP play with sipp 3.6 is broken or please let me know why it works with 3.3.990

### ISSUE THREAD

**Issue by mhanuel26** [SIPp/sipp#223]
I have spent some time trying to send a simple .pcap audio stream using sipp version 3.6 without success, my server is running uas.xml file unmodified, the command for server is

sipp -sf /home/myusernamehere/Devel/sipp-scenarios/uas.xml -mi 192.168.3.7

the client is using the uac_pcap.xml file unmodified too, the one that sends the g711a.pcap and dtmf_2833_1.pcap.

The client command is

/sipp -sf /home/myusernamehere/Devel/SIP/sipp-scenarios/uac_pcap.xml 192.168.3.7 -mi 192.168.3.5 -m 1

Using same commands and scenarios but with version 3.3.99 it works. 

The way I am determining it doesn't work is capturing outgoing traffic with tcpdump and reading file in wioreshark, the version 3.6 seems to send RTP packets with all zeros in UDP/RTP/Payload and so length is 36780, also I notice that for some reason the packet numbering in wireshark and the counted by tcpdump as captured is ridiculous big, for the example above it should be 251 or so, and with version 3.6 the count is 5663, a further inspection shows that there are the same number of RTP packets (bad as explained before) but numbering on wireshark makes jumps in sequence to get to 5k.

Also, one more thing that might be wrong is that when running client with version 3.6 is claims about some packet bigger that some define, the error is

2016-04-19      18:24:42.274355 1461104682.274355: Packet size is too big! Recompile with bigger PCAP_MAXPACKET in prepare_pcap.h.

I increase the size in definition (don't blame me if this is the reason but rather let me know how to fix the error) in

#define PCAP_MAXPACKET 1500

to some bigger number and it allow me to run.

Version 3.3.99 don't suffer from this at all.

Don't know how to upload the captures, as .zip the page won't accept it.

**Comment by vodik** [comment]
Can you upload them somewhere like Dropbox? I'd gladly look at it if you can share those files.

**Comment by mhanuel26** [comment]
For sure, 
Here are the captures, 
https://www.dropbox.com/sh/nu0c38c9g5arc4l/AABMQf-ijg3qSsYZzi3lmODya?dl=0
I am working with 3.3.990 and so far I can send RTP traffic, I also attach an .xml anmd .pcap with PCMU RTP payload I have successfully transmit to another linux host running the server. 
Just let me know, I can do some more tests if you need but have limited knowledge about sipp sources...

**Comment by vodik** [comment]
Thanks! I grabbed everything and I'll see what I can dig up this weekend. I'll hopefully get back to you soon.

**Comment by vodik** [comment]
Alright, I'm seeing this issue in production too, on the case.

**Comment by vodik** [comment]
Give it a go and report back. Thanks for the information!
