### ISSUE TITLE
Migrate SIPp documentation (probably to Sphinx/ ReadTheDocs.io)

### ISSUE THREAD

**Issue by thisismyname** [SIPp/sipp#226]
Get the old documentation from sourceforge and place them in rst or md-Style inside a ./docs subdirectory. After that you could register the project ar readthedocs.io and get nicely formatted documentation.
Currently SIPp is not very beginnerfriendly with a "3.4(current)" documentation from sourceforge.

If there is no reason not to do so, I'd be happy to create a pull request.

**Comment by lemenkov** [comment]
@thisismyname great idea! Please go on! :)

**Comment by pbertera** [comment]
This is very a good idea, I would suggest to use Markdown and Mkdocs instead of Sphinx and reStructured text.
I found Mkdocs more simple and straightforward then Sphinx, Markdown is quite simple and intuitive: contributing and maintaining the documentation will be more easy.

Then we should easily use Github pages to deploy the documentation.
How can we go forward on this topic ?

Thanks,

**Comment by wdoekes** [comment]
I'm sorry, but Markdown is really only suited for the simplest of tasks. And if there already are reStructuredtext samples to look at when adding more content, I don't think anyone will have problems contributing.

That being said, markdown documentation beats no documentation ;)

**Comment by nshopik** [comment]
@wdoekes I'm working on rst version. 

So just heads up if anyone already started to avoid double work

**Comment by nshopik** [comment]
So I've been converted most docs except large tables. So would like to hear opinion on large tables what todo with them. 

If I convert to rst as it is they won't look pretty in plain text rst files, but surely look same in html after compilation. But maybe we should rework them, thoughs?

**Comment by wdoekes** [comment]
I've been struggling with rst and tables lately.

For one, you'll want to use an editor plugin to help you, so you can rewrap/reformat quickly.

Secondly, trying to fit everything in 72 chars is not always an option. There are a few ways to cope:
- flatten the data (alter the representation so you don't need 4+ columns)
- change texts to icons (using replaceable's)
- expand up to ~120 columns (I don't think you'll want to go wider than that)

It depends on the situation which to apply.

Having said that, you could certainly upload/PR the docs with overwide tables and create tickets to fix those afterwards.

**Comment by nshopik** [comment]
I've tried to convert them in plain text and most of them doesn't even fit into 120 columns if you want them look pretty in plain text. Personally I'd rather avoid icons when possible.

So I'll work on change representation. Will post WIP later on

**Comment by wdoekes** [comment]
I added `sipp-wip` into rtd: http://sipp-wip.readthedocs.io/en/latest/

The `sipp` rtd already existed and is adminned by @rkday. But because the documentation isn't up to par yet, it's not a problem that it's not under the right rtd subdomain yet.

Note to self: github does not do 2 rtd webhooks, so there is no auto-building when committing to master.

**Comment by nshopik** [comment]
Regarding tables, there is extension to Sphinx made by kernel devs to their documentation called flat-table
https://github.com/torvalds/linux/blob/master/Documentation/sphinx/rstFlatTable.py and it doesn't look like mess in rst. 

rst example https://www.kernel.org/doc/html/latest/_sources/media/uapi/v4l/vidioc-enuminput.txt will result this output https://www.kernel.org/doc/html/latest/media/uapi/v4l/vidioc-enuminput.html

**Comment by nshopik** [comment]
@wdoekes What should we do with integrated scenarios files (uac.xml, uas.xml, etc), should I import them into docs dir? We could reference them from other location in repo to avoid having duplicates

**Comment by wdoekes** [comment]
Re: tables:
- I like that FlatTable idea.

Re: scenario files:
- yes, putting them in the docs/ dir sounds like a plan,
- possibly with a make command that runs `./sipp -sd ...` to update them

**Comment by nshopik** [comment]
This issue can be closed as we completely migrated whole documentation now

**Comment by lemenkov** [comment]
Ok, closing this.
