### ISSUE TITLE
Win32 port

### ISSUE THREAD

**Issue by rkday** [SIPp/sipp#23]
SIPped, the Polycom fork of SIPp (https://github.com/SIPp/polycom-sipped) compiles natively on Widows with Visual Studio (i.e. without Cygwin). It would be good to get this merged into the main SIPp code.

It looks as though the relevant commits are a5011a6, 57220e0, d3a4b09, ac0cb41, cafe0f3, 3b96e94, 7dc7c0a, 07dddd1, 428a2ea, 37f9d19, 1776d34, 8c0d813, 8df0de5, 7c2df78, d63f0a5, 49763eb, 57fe216, 5b6f12c, 2c50756, f68cfe8, ba3fdf6, 4700588, 331c6ed, 1ad906e, ee4c148, 20d6457, 95bec90, 5098602, 1a36dba, 892a9e2, 3072d2c and 981909.

**Comment by orgads** [comment]
This can be closed. sipp can be built using mingw without any cygwin/msys dependencies.

**Comment by wdoekes** [comment]
Cool. Thanks for the comment :+1:

**Comment by orgads** [comment]
Sorry, but I was wrong about that. MSYS/Cygwin is still required for building sipp. There are dependencies on sys/socket.h, sys/wait.h and more.

**Comment by sskras** [comment]
I tried building sipp on [Midipix](https://github.com/lalbornoz/midipix_build#1-what-is-midipix-and-how-is-it-different) (a more effective alternative to Cygwin and MSYS2).
It seems to lack recent gcc and thus a support of C++11 too:
```sh
midipix@DESKTOP-O7JE7JE /dev/mnt/d/_BACKUPS/src/github.com/SIPp/sipp
$ make
Scanning dependencies of target version
[  0%] Built target version
Scanning dependencies of target sipp
[  2%] Building CXX object CMakeFiles/sipp.dir/src/actions.cpp.o
cc1plus: error: unrecognized command line option '-std=c++11'
make[2]: *** [CMakeFiles/sipp.dir/build.make:63: CMakeFiles/sipp.dir/src/actions.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:132: CMakeFiles/sipp.dir/all] Error 2
make: *** [Makefile:128: all] Error 2
```
```sh
midipix@DESKTOP-O7JE7JE /dev/mnt/d/_BACKUPS/src/github.com/SIPp/sipp
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/bin/../libexec/gcc/x86_64-nt64-midipix/4.6.4/lto-wrapper
Target: x86_64-nt64-midipix
Configured with: ../cbb-gcc-4.6.4/configure --disable-sjlj-exceptions --host=x86_64-nt64-midipix --prefix=/ --with-elf=/home/saukrs/midipix/nt64/release/native --with-gmp=/home/saukrs/midipix/nt64/release/native --with-mpc=/home/saukrs/midipix/nt64/release/native --with-mpfr=/home/saukrs/midipix/nt64/release/native --with-sysroot= --disable-bootstrap --disable-libmudflap --disable-multilib --disable-nls --disable-obsolete --disable-symvers --enable-canonical-system-headers --enable-__cxa_atexit --enable-debug --enable-gnu-indirect-function --enable-gnu-unique-object --enable-initfini-array --enable-languages=c,c++,fortran,objc,lto --enable-libstdcxx-debug --enable-lto --enable-multiarch --enable-secureplt --enable-shared --enable-threads=posix --target=x86_64-nt64-midipix --with-fpmath=sse
Thread model: posix
gcc version 4.6.4 (GCC)
```
```sh
midipix@DESKTOP-O7JE7JE /dev/mnt/d/_BACKUPS/src/coreutils-9.3-DEV
$ uname -a
midipix DESKTOP-O7JE7JE pre-alpha-internal-2bc731105275d52feb98f3b47cf454e7674ab739 2022.11.18.20.22.52 x86_64 Midipix
```

It looks like **Midipix** will have to upgrade its' GCC build to [version 4.7](https://gcc.gnu.org/gcc-4.7/cxx0x_status.html), at least:
https://gcc.gnu.org/projects/cxx-status.html#cxx11
