### ISSUE TITLE
Problem with removed media section in the SDP

### ISSUE THREAD

**Issue by EltexTester** [SIPp/sipp#230]
Hello! I have a problem. If I send the following SDP to SIPp:

> v=0
> o=ecss 973455308698 973455308700 IN IP4 192.168.118.245
> s=pjmedia
> b=AS:84
> t=0 0
> a=X-nat:0
> m=audio 0 RTP/AVP 8
> c=IN IP4 127.0.0.1
> m=video 0 RTP/AVP 34
> c=IN IP4 127.0.0.1
> m=audio 12176 RTP/AVP 8
> c=IN IP4 192.168.118.224
> b=TIAS:64000
> a=rtpmap:8 PCMA/8000/1
> a=rtcp:12177 IN IP4 192.168.118.224
> a=sendrecv
> 

then I receive error:
> extract_rtp_remote_addr: no m=audio, m=image or m=video line found in SDP message body.

**Comment by vodik** [comment]
Sorry for the slow response, is it possible you can provide a pcap? If its a bug in SIPp, I don't think its a bug with our SDP handling, it runs through cleanly when I plug it into a unit test.

**Comment by wdoekes** [comment]
No time response. Please reopen if you can provide the missing info.
