### ISSUE TITLE
Abnormal program Termination GIT include/version.h

### ISSUE THREAD

**Issue by saurabh162** [SIPp/sipp#231]
Hello, 

Please tell me the reason and solution of following error

I received following error I give "make CROSS_COMPILE=arm-cortexm3-eabi-
" in src folder of GitHub Blackmagic project as mentioned in its hack file.

In addtion to this I am using windows 7 and unxutils to run linux commands on windows. Kindly inform me if you need any other information

**Error:**
GIT     include/version.h

abnormal program termination
C:\Users\saurabh\AppData\Local\Temp\make199443.sh: fork failed: no error [1]
make: *** [include/version.h] Error 1

Thanks and Regards 

Saurabh Jain

**Comment by wdoekes** [comment]
Hi there @saurabh162.

Your environment seems woefully incomplete.

Generating include/version.h is done by the (generated) Makefile. The generated makefile should contain this bit from `m4/am_git_version.mh`:
```git_version = $(shell git describe --tags --always 2>/dev/null || cat .version 2>/dev/null)
file_version = $(shell cat .version 2>/dev/null)
ifneq ($(git_version),$(file_version))
    $(shell echo 'Updating include/version.h' >&2)
    $(shell echo '#define SIPP_VERSION "$(git_version)"' >include/version.h)
    $(shell echo '$(git_version)' >.version)
endif
```

**Comment by saurabh162** [comment]
Hello wdoekes

I doubt my development environment. Actually I am using unxutils on Windows to run makefile. 
I will use hints provided by you and will update you.

Thanks and Regards 
Saurabh Jain

**Comment by wdoekes** [comment]
(I'll label this as invalid in the mean time, until there really is a bug.)

**Comment by wdoekes** [comment]
No timely response. Please reopen if still relevant.
