### ISSUE TITLE
ld missing commandline arg for libtinfo.so

### ISSUE THREAD

**Issue by 257** [SIPp/sipp#239]
on gentoo i get this: [make.log](https://gist.github.com/05e323c230e918af85cf500ce4101702)
solution here migh help: [neomutt](https://github.com/neomutt/neomutt/issues/65`)

**Comment by wdoekes** [comment]
Relevant:

http://stackoverflow.com/questions/26348743/curses-development-kit-dso-missing-from-command-line

https://moc.daper.net/node/1469

**Comment by wdoekes** [comment]
Fixed in 90f38e46. Thanks for the report.
