### ISSUE TITLE
Call to regexec() in src/actions.cpp references wrong flag, causing the begining of line anchor (^) to be misinterpreted

### ISSUE THREAD

**Issue by jeromegrenier** [SIPp/sipp#242]
Hi,

In include/variables.hpp, we have:

`#define REGEXP_PARAMS REG_EXTENDED`

And in src/actions.cpp, we have:

`error = regexec(&M_internalRegExp, P_string, 10, pmatch, REGEXP_PARAMS);`

The issue is that "REG_EXTENDED" (a flag defined for regcomp()), has the same integer value as "REG_NOTBOL", one of the flags actually defined for regexec(). So regexec() is actually being invoked as if "REG_NOTBOL" had been used. The outcome is that using a begining of line anchor (^) in an ereg's "regexp" attribute is rather interpreted as a plain (non-special) circumflex character. This does not match the common expectation for this symbol.

The solution would be to invoke it without any flags (0):

`error = regexec(&M_internalRegExp, P_string, 10, pmatch, 0);`

... similar to how it is invoked in src/call.cpp:

`return !regexec(curmsg -> regexp_compile, request, (size_t)0, NULL, 0);`

Thanks,

Jérôme

**Comment by wdoekes** [comment]
Fixed in 3.6 by 9e90af8dcbe6ed4cdf210f73ead89c0024d1b569. Thanks for the report. Sorry for the late followup.
