### ISSUE TITLE
Unable to bind audio RTP socket

### ISSUE THREAD

**Issue by sjthomason** [SIPp/sipp#246]
After commit 4aa361d5aefc080d32d96134c9d7493a1eeee564, OS X builds fail to bind with the error:
Unable to bind audio RTP socket (IP=X.X.X.X, port=6100), errno = 22 (Invalid argument).

I did a git bisect and found that the previous commit works correctly.

**Comment by wdoekes** [comment]
You're right.

All replacements in the bind(), connect() and sendto() functions are wrong in that commit.
I'm sorry that code review didn't catch that.

Thanks for bisecting! I'll get a fix for this up shortly.

**Comment by sjthomason** [comment]
Hi @wdoekes looks like get_inet_address() needs this too.

Thanks!

**Comment by wdoekes** [comment]
Indeed it does. Pushed an updated version. Thanks!
