### ISSUE TITLE
variable usage requirements

### ISSUE THREAD

**Issue by sgel83** [SIPp/sipp#248]
[root@trials sipp]# sipp_351 -sf 3gpp-uas_reg_auth.xml -i 10.10.10.100 -ci 10.10.10.100
2016-08-24      15:16:33.451011 1472048193.451011: Variable $dummy is referenced 1 times!

The following error is being issued due to the fact that the variable is not used anywhere else in the script.

This is in fact the case but necessary due to the sub string return of regex

```
  <recv request="REGISTER" crlf="true">
  	<action>
  		<ereg regexp="<sip:(.*)@(.*)>" search_in="hdr" header="From:" check_it="true" assign_to="uri,user,host" />
  	</action>
  </recv>

```
Basically only the user/host part is necessary for later in the script.  

      P-Associated-URI: sip:[$user]@[$host]
      P-Associated-URI: tel:[$user]

It shouldn't be required to use all substrings returned from regex.

A work around is just to do the following:

`<assignstr assign_to="dummy" value="[$dummy]" />`

**Comment by wdoekes** [comment]
Right now the canonical way is to use `<Reference/>`:

http://sipp.sourceforge.net/doc/reference.html
```
<Reference>	variables	Suppresses warnings about unused variables.	<Reference variables="dummy" />
```

**Comment by wdoekes** [comment]
This is a documentation issue. See also #52.
