### ISSUE TITLE
sipp missing the first REGISTER message

### ISSUE THREAD

**Issue by wangweinwu** [SIPp/sipp#249]
When I use the sipp with the register_client script file, sometimes through the Wireshark capture display will be missing the first user REGISTER message, but in the SIPP print interface and MSG files showed the message has been sent.This situation often occurs in the higher rate, for example, more than 10CPS.

**Comment by wdoekes** [comment]
Might be related to #164 (worked around by disabling epoll). Closing for now, as this is hard to reproduce.
