### ISSUE TITLE
Build sipp-3.5.1 issue: error: ISO C++ does not support 'long long'

### ISSUE THREAD

**Issue by jaseermohammed** [SIPp/sipp#250]
Hi, 

I tried build sipp-3.5.1 using the below command
```
./build.sh --full
```
I have installed all the dependencies, but i get the below error now
```
/include/stat.hpp:307: error: ISO C++ does not support â€˜long longâ€™
```

```
rm -f src/sipp_unittest-time.o
rm -f src/sipp_unittest-variables.o
rm -f src/sipp_unittest-watchdog.o
rm -f src/sipp_unittest-xp_parser.o
rm -f src/sipp_unittest-xp_parser_ut.o
g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -Dis_default_constructible=is_nothrow_constructible -I./include -Wall -pedantic  -g -O2 -MT src/sipp-actions.o -MD -MP -MF src/.deps/sipp-actions.Tpo -c -o src/sipp-actions.o `test -f 'src/actions.cpp' || echo './'`src/actions.cpp
g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -Dis_default_constructible=is_nothrow_constructible -I./include -Wall -pedantic  -g -O2 -MT src/sipp-auth.o -MD -MP -MF src/.deps/sipp-auth.Tpo -c -o src/sipp-auth.o `test -f 'src/auth.cpp' || echo './'`src/auth.cpp
gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -Dis_default_constructible=is_nothrow_constructible -I./include -Wall -pedantic  -g -O2 -D__LINUX -MT src/sipp-comp.o -MD -MP -MF src/.deps/sipp-comp.Tpo -c -o src/sipp-comp.o `test -f 'src/comp.c' || echo './'`src/comp.c
src/comp.c: In function â€˜comp_loadâ€™:
src/comp.c:42: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/comp.c:48: warning: dereferencing type-punned pointer will break strict-aliasing rules
src/comp.c:54: warning: dereferencing type-punned pointer will break strict-aliasing rules
mv -f src/.deps/sipp-comp.Tpo src/.deps/sipp-comp.Po
g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -Dis_default_constructible=is_nothrow_constructible -I./include -Wall -pedantic  -g -O2 -MT src/sipp-call.o -MD -MP -MF src/.deps/sipp-call.Tpo -c -o src/sipp-call.o `test -f 'src/call.cpp' || echo './'`src/call.cpp
./include/stat.hpp:307: error: ISO C++ does not support â€˜long longâ€™
./include/stat.hpp:307: error: ISO C++ does not support â€˜long longâ€™
./include/stat.hpp:314: error: ISO C++ does not support â€˜long longâ€™
./include/stat.hpp:420: error: ISO C++ does not support â€˜long longâ€™
```

Can you please let me know how to resolve this issue .

Thanks,
Jaseer

**Comment by wdoekes** [comment]
You appear have a combination of an old and strict gcc.

What does `gcc --version` say? I can't tell why it defaults to erroring there.

I can reproduce it if I add `-pedantic-errors` or `-Werror`:

```
$ touch src/task.cpp 
$ make CXXFLAGS='-pedantic-errors'
g++ -DHAVE_CONFIG_H   -DRTP_STREAM   -DHAVE_EPOLL -I. -I./include   -D__LINUX -Dis_default_constructible=is_nothrow_constructible -I./include -Wall -pedantic  -pedantic-errors -MT src/sipp-task.o -MD -MP -MF src/.deps/sipp-task.Tpo -c -o src/sipp-task.o `test -f 'src/task.cpp' || echo './'`src/task.cpp
In file included from ./include/scenario.hpp:32:0,
                 from ./include/sipp.hpp:71,
                 from src/task.cpp:46:
./include/stat.hpp:307:23: error: ISO C++ 1998 does not support ‘long long’ [-Wlong-long]
```

So, you need the inverse. While there is an inverse for `-Werror`, there isn't for `-pedantic-errors`.

Try this:
```
make CXXFLAGS='-Wno-error'
```

If that doesn't help, try this:

```
sed -i -e 's/-pedantic//' Makefile.am Makefile.in Makefile
make
```

**Comment by wdoekes** [comment]
And I'm curious about the output of:
```
gcc -Q --help=warnings
```

**Comment by wdoekes** [comment]
@jaseermohammed: can you provided the requested info?

**Comment by wdoekes** [comment]
No timely response.

**Comment by aparnaannapragada** [comment]
I know it has been a long time, but was seeing this issue while installing sipp-3.6.0

gcc version is 4.6.3

Tried the 2 options mentioned:

`make CXXFLAGS='-Wno-error'`

and 
 `sed -i -e 's/-pedantic//' Makefile.am Makefile.in Makefile
make`

This is the error being seen:

`make  all-am
make[1]: Entering directory `/home/test/annlaksh/sipp-3.6.0'
g++ -DHAVE_CONFIG_H -DUSE_TLS -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM   -DHAVE_EPOLL -I. -I./include  -D_BSD_SOURCE -D_DEFAULT_SOURCE -D__LINUX -Dis_default_constructible=is_nothrow_constructible -I./include -Wall   -Wno-error -MT src/sipp-call.o -MD -MP -MF src/.deps/sipp-call.Tpo -c -o src/sipp-call.o `test -f 'src/call.cpp' || echo './'`src/call.cpp
src/call.cpp:3267:13: warning: identifier 'nullptr' will become a keyword in C++0x [-Wc++0x-compat]
src/call.cpp: In member function 'call::T_ActionResult call::executeAction(const char*, message*)':
src/call.cpp:3267:36: error: 'nullptr' was not declared in this scope
make[1]: *** [src/sipp-call.o] Error 1
make[1]: Leaving directory `/home/test/annlaksh/sipp-3.6.0'
make: *** [all] Error 2
`


`The following options control compiler warning messages:
  --all-warnings              		
  --extra-warnings            		
  -W                          		
  -Wabi                       		[disabled]
  -Waddress                   		[disabled]
  -Waggregate-return          		[disabled]
  -Waliasing                  		
  -Walign-commons             		
  -Wall                       		
  -Wampersand                 		
  -Warray-bounds              		[disabled]
  -Warray-temporaries         		
  -Wassign-intercept          		[disabled]
  -Wattributes                		[enabled]
  -Wbad-function-cast         		[disabled]
  -Wbuiltin-macro-redefined   		
  -Wc++-compat                		[disabled]
  -Wc++0x-compat              		[disabled]
  -Wcast-align                		[disabled]
  -Wcast-qual                 		[disabled]
  -Wchar-subscripts           		[disabled]
  -Wcharacter-truncation      		
  -Wclobbered                 		[enabled]
  -Wcomment                   		
  -Wcomments                  		
  -Wconversion                		[disabled]
  -Wconversion-extra          		
  -Wconversion-null           		[enabled]
  -Wcoverage-mismatch         		[enabled]
  -Wcpp                       		[enabled]
  -Wctor-dtor-privacy         		[disabled]
  -Wdeclaration-after-statement 	[disabled]
  -Wdeprecated                		[enabled]
  -Wdeprecated-declarations   		[enabled]
  -Wdisabled-optimization     		[disabled]
  -Wdiv-by-zero               		[enabled]
  -Wdouble-promotion          		[disabled]
  -Weffc++                    		[disabled]
  -Wempty-body                		[enabled]
  -Wendif-labels              		
  -Wenum-compare              		[enabled]
  -Werror-implicit-function-declaration 	
  -Wextra                     		[disabled]
  -Wfloat-equal               		[disabled]
  -Wformat                    		
  -Wformat-contains-nul       		[disabled]
  -Wformat-extra-args         		[disabled]
  -Wformat-nonliteral         		[disabled]
  -Wformat-security           		[enabled]
  -Wformat-y2k                		[disabled]
  -Wformat-zero-length        		[disabled]
  -Wformat=                   		
  -Wignored-qualifiers        		[enabled]
  -Wimplicit                  		[enabled]
  -Wimplicit-function-declaration 	[enabled]
  -Wimplicit-int              		[enabled]
  -Wimplicit-interface        		
  -Wimplicit-procedure        		
  -Winit-self                 		[disabled]
  -Winline                    		[disabled]
  -Wint-to-pointer-cast       		[enabled]
  -Wintrinsic-shadow          		
  -Wintrinsics-std            		
  -Winvalid-offsetof          		[enabled]
  -Winvalid-pch               		
  -Wjump-misses-init          		[enabled]
  -Wlarger-than-              		
  -Wlarger-than=<number>      		
  -Wline-truncation           		
  -Wlogical-op                		[disabled]
  -Wlong-long                 		[enabled]
  -Wmain                      		[enabled]
  -Wmissing-braces            		[disabled]
  -Wmissing-declarations      		[disabled]
  -Wmissing-field-initializers 		[enabled]
  -Wmissing-format-attribute  		[disabled]
  -Wmissing-include-dirs      		
  -Wmissing-noreturn          		[disabled]
  -Wmissing-parameter-type    		[enabled]
  -Wmissing-prototypes        		[disabled]
  -Wmudflap                   		[enabled]
  -Wmultichar                 		
  -Wnested-externs            		[disabled]
  -Wnoexcept                  		[disabled]
  -Wnon-template-friend       		[enabled]
  -Wnon-virtual-dtor          		[disabled]
  -Wnonnull                   		[disabled]
  -Wnormalized=<id|nfc|nfkc>  		
  -Wold-style-cast            		[disabled]
  -Wold-style-declaration     		[enabled]
  -Wold-style-definition      		[disabled]
  -Woverflow                  		[enabled]
  -Woverlength-strings        		[enabled]
  -Woverloaded-virtual        		[disabled]
  -Woverride-init             		[enabled]
  -Wpacked                    		[disabled]
  -Wpacked-bitfield-compat    		[enabled]
  -Wpadded                    		[disabled]
  -Wparentheses               		[disabled]
  -Wpmf-conversions           		[enabled]
  -Wpointer-arith             		[disabled]
  -Wpointer-sign              		[enabled]
  -Wpointer-to-int-cast       		[enabled]
  -Wpragmas                   		[enabled]
  -Wproperty-assign-default   		[enabled]
  -Wprotocol                  		[enabled]
  -Wreal-q-constant           		
  -Wredundant-decls           		[disabled]
  -Wreorder                   		[disabled]
  -Wreturn-type               		[disabled]
  -Wselector                  		[disabled]
  -Wsequence-point            		[disabled]
  -Wshadow                    		[disabled]
  -Wsign-compare              		[enabled]
  -Wsign-promo                		[disabled]
  -Wstack-protector           		[disabled]
  -Wstrict-aliasing           		
  -Wstrict-aliasing=          		0xffffffff
  -Wstrict-null-sentinel      		[disabled]
  -Wstrict-overflow           		
  -Wstrict-overflow=          		0xffffffff
  -Wstrict-prototypes         		[disabled]
  -Wstrict-selector-match     		[disabled]
  -Wsuggest-attribute=const   		[disabled]
  -Wsuggest-attribute=noreturn 		[disabled]
  -Wsuggest-attribute=pure    		[disabled]
  -Wsurprising                		
  -Wswitch                    		[disabled]
  -Wswitch-default            		[disabled]
  -Wswitch-enum               		[disabled]
  -Wsync-nand                 		[enabled]
  -Wsynth                     		[disabled]
  -Wsystem-headers            		[disabled]
  -Wtabs                      		
  -Wtraditional               		[disabled]
  -Wtraditional-conversion    		[disabled]
  -Wtrampolines               		[disabled]
  -Wtrigraphs                 		
  -Wtype-limits               		[enabled]
  -Wundeclared-selector       		[disabled]
  -Wundef                     		
  -Wunderflow                 		
  -Wuninitialized             		[enabled]
  -Wunknown-pragmas           		
  -Wunsafe-loop-optimizations 		[disabled]
  -Wunsuffixed-float-constants 		[disabled]
  -Wunused                    		[disabled]
  -Wunused-but-set-parameter  		[enabled]
  -Wunused-but-set-variable   		[enabled]
  -Wunused-dummy-argument     		
  -Wunused-function           		[enabled]
  -Wunused-label              		[enabled]
  -Wunused-macros             		
  -Wunused-parameter          		[enabled]
  -Wunused-result             		[enabled]
  -Wunused-value              		[enabled]
  -Wunused-variable           		[enabled]
  -Wvariadic-macros           		
  -Wvla                       		[enabled]
  -Wvolatile-register-var     		[disabled]
  -Wwrite-strings             		[disabled]
  -frequire-return-statement  		[enabled]

`

**Comment by aparnaannapragada** [comment]
Okay...Sorry about reopening this thread.
Edited the files and changed 'nullptr' to 'NULL' for now.
