### ISSUE TITLE
RTPSTREAM is playing only mono(single) not stereo(two channels)

### ISSUE THREAD

**Issue by vijayphalgun** [SIPp/sipp#266]
Observed that when used a wav file with two streams(stereo) the audio is garbled not working properly but when using a mono stream(single channel) its working fine.

**Comment by wdoekes** [comment]
What were you expecting? When you look at the number of channels in the following list, you'll notice that most of them are fixed to 1 (mono):
https://en.wikipedia.org/wiki/RTP_audio_video_profile

Adding stereo support by downmixing seems unnecessary: you should do that when making the wav. Playing stereo is probably a matter of choosing Payload type 10 (2 channels). If that's not possible with RTPSTREAM perhaps that needs to be enhanced; please file a different ticket for that.
