### ISSUE TITLE
Build fails with error: undefined reference to gsl

### ISSUE THREAD

**Issue by leonroy** [SIPp/sipp#275]
Trying to compile 3.5.1 on Ubuntu 16.0.4.

Installed the following dependencies:

    dh-autoreconf ncurses-dev build-essential libssl-dev libpcap-dev libncurses5-dev libsctp-dev lksctp-tools libgsl0-dev

Seeing the following error when executing `build.sh --full`:

    root@sipp:~/sipp# ./build.sh --full

Output:

	Submodule 'gmock' (https://chromium.googlesource.com/external/googlemock) registered for path 'gmock'
	Submodule 'gtest' (https://chromium.googlesource.com/external/googletest) registered for path 'gtest'
	Cloning into 'gmock'...
	remote: Total 2287 (delta 1611), reused 2287 (delta 1611)
	Receiving objects: 100% (2287/2287), 1.01 MiB | 0 bytes/s, done.
	Resolving deltas: 100% (1611/1611), done.
	Checking connectivity... done.
	Submodule path 'gmock': checked out 'c7ee6b5c206e498063b1e89d381045f78cb6ab36'
	Cloning into 'gtest'...
	remote: Total 4343 (delta 3230), reused 4343 (delta 3230)
	Receiving objects: 100% (4343/4343), 1.69 MiB | 0 bytes/s, done.
	Resolving deltas: 100% (3230/3230), done.
	Checking connectivity... done.
	Submodule path 'gtest': checked out '935f1265d088d81e802c49aec8cb717c30741caa'
	autoreconf: Entering directory `.'
	autoreconf: configure.ac: not using Gettext
	autoreconf: running: aclocal --force
	autoreconf: configure.ac: tracing
	autoreconf: configure.ac: not using Libtool
	autoreconf: running: /usr/bin/autoconf --force
	autoreconf: running: /usr/bin/autoheader --force
	autoreconf: running: automake --add-missing --force-missing
	configure.ac:42: installing './compile'
	configure.ac:14: installing './config.guess'
	configure.ac:14: installing './config.sub'
	configure.ac:18: installing './install-sh'
	configure.ac:18: installing './missing'
	Makefile.am: installing './depcomp'
	parallel-tests: installing './test-driver'
	autoreconf: Leaving directory `.'
	checking build system type... x86_64-pc-linux-gnu
	checking host system type... x86_64-pc-linux-gnu
	checking target system type... x86_64-pc-linux-gnu
	checking for a BSD-compatible install... /usr/bin/install -c
	checking whether build environment is sane... yes
	checking for a thread-safe mkdir -p... /bin/mkdir -p
	checking for gawk... gawk
	checking whether make sets $(MAKE)... yes
	checking whether make supports nested variables... yes
	checking for help2man... no
	configure: WARNING: cannot find help2man, you will not be able to generate manpages
	checking for gcc... gcc
	checking whether the C compiler works... yes
	checking for C compiler default output file name... a.out
	checking for suffix of executables...
	checking whether we are cross compiling... no
	checking for suffix of object files... o
	checking whether we are using the GNU C compiler... yes
	checking whether gcc accepts -g... yes
	checking for gcc option to accept ISO C89... none needed
	checking whether gcc understands -c and -o together... yes
	checking for style of include used by make... GNU
	checking dependency style of gcc... gcc3
	checking for g++... g++
	checking whether we are using the GNU C++ compiler... yes
	checking whether g++ accepts -g... yes
	checking dependency style of g++... gcc3
	checking how to run the C preprocessor... gcc -E
	checking for grep that handles long lines and -e... /bin/grep
	checking for egrep... /bin/grep -E
	checking for ANSI C header files... yes
	checking whether g++ supports C++11 features by default... no
	checking whether g++ supports C++11 features with -std=gnu++11... yes
	checking whether C compiler accepts -std=gnu11... yes
	checking for initscr in -lcurses... yes
	checking for pthread_mutex_init in -lpthread... yes
	checking for library containing dlopen... -ldl
	checking for library containing dlerror... none required
	checking for library containing dlsym... none required
	checking for library containing clock_gettime... none required
	checking for library containing inet_addr... none required
	checking for library containing inet_ntoa... none required
	checking for library containing pthread_mutex_init... none required
	checking for library containing pthread_mutex_destroy... none required
	checking for library containing pthread_mutex_lock... none required
	checking for library containing pthread_mutex_unlock... none required
	checking for library containing pthread_self... none required
	checking for library containing pthread_cancel... -lpthread
	checking for library containing pthread_join... none required
	checking for library containing pthread_attr_init... none required
	checking for library containing pthread_attr_setstacksize... none required
	checking for library containing pthread_create... none required
	checking for library containing pthread_attr_destroy... none required
	checking for library containing pthread_setschedparam... none required
	checking for library containing pthread_setcancelstate... none required
	checking for library containing pthread_setcanceltype... none required
	checking for library containing pthread_exit... none required
	checking for library containing pthread_sigmask... none required
	checking for library containing floor... -lm
	checking for library containing pow... none required
	checking for library containing htons... none required
	checking for library containing ntohs... none required
	checking for library containing bind... none required
	checking for library containing freeaddrinfo... none required
	checking for library containing getaddrinfo... none required
	checking for library containing listen... none required
	checking for library containing recvfrom... none required
	checking for library containing shutdown... none required
	checking for sys/types.h... yes
	checking for sys/stat.h... yes
	checking for stdlib.h... yes
	checking for string.h... yes
	checking for memory.h... yes
	checking for strings.h... yes
	checking for inttypes.h... yes
	checking for stdint.h... yes
	checking for unistd.h... yes
	checking openssl/md5.h usability... yes
	checking openssl/md5.h presence... yes
	checking for openssl/md5.h... yes
	checking openssl/bio.h usability... yes
	checking openssl/bio.h presence... yes
	checking for openssl/bio.h... yes
	checking openssl/err.h usability... yes
	checking openssl/err.h presence... yes
	checking for openssl/err.h... yes
	checking openssl/rand.h usability... yes
	checking openssl/rand.h presence... yes
	checking for openssl/rand.h... yes
	checking openssl/ssl.h usability... yes
	checking openssl/ssl.h presence... yes
	checking for openssl/ssl.h... yes
	checking openssl/x509v3.h usability... yes
	checking openssl/x509v3.h presence... yes
	checking for openssl/x509v3.h... yes
	checking for SSL_library_init in -lssl... yes
	checking for CRYPTO_num_locks in -lcrypto... yes
	checking netinet/sctp.h usability... yes
	checking netinet/sctp.h presence... yes
	checking for netinet/sctp.h... yes
	checking for library containing sctp_send... -lsctp
	checking for library containing sctp_freepaddrs... none required
	checking for library containing sctp_bindx... none required
	checking for library containing sctp_recvmsg... none required
	checking pcap.h usability... yes
	checking pcap.h presence... yes
	checking for pcap.h... yes
	checking for library containing pcap_open_offline... -lpcap
	checking for library containing pcap_next... none required
	checking for library containing pcap_close... none required
	checking for pcap_next_ex in -lpcap... yes
	checking gsl/gsl_randist.h usability... yes
	checking gsl/gsl_randist.h presence... yes
	checking for gsl/gsl_randist.h... yes
	checking gsl/gsl_rng.h usability... yes
	checking gsl/gsl_rng.h presence... yes
	checking for gsl/gsl_rng.h... yes
	checking gsl/gsl_cdf.h usability... yes
	checking gsl/gsl_cdf.h presence... yes
	checking for gsl/gsl_cdf.h... yes
	checking for cos in -lm... yes
	checking for cblas_dgemm in -lgslcblas... yes
	checking for gsl_rng_alloc in -lgsl... yes
	./configure: line 8266: pkg-config: command not found
	./configure: line 8267: pkg-config: command not found
	./configure: line 8268: pkg-config: command not found
	checking linux/version.h usability... yes
	checking linux/version.h presence... yes
	checking for linux/version.h... yes
	checking for Linux epoll(7) interface... yes
	checking for size_t... yes
	checking for working alloca.h... yes
	checking for alloca... yes
	checking arpa/inet.h usability... yes
	checking arpa/inet.h presence... yes
	checking for arpa/inet.h... yes
	checking fcntl.h usability... yes
	checking fcntl.h presence... yes
	checking for fcntl.h... yes
	checking limits.h usability... yes
	checking limits.h presence... yes
	checking for limits.h... yes
	checking netdb.h usability... yes
	checking netdb.h presence... yes
	checking for netdb.h... yes
	checking netinet/in.h usability... yes
	checking netinet/in.h presence... yes
	checking for netinet/in.h... yes
	checking for stdlib.h... (cached) yes
	checking for string.h... (cached) yes
	checking sys/socket.h usability... yes
	checking sys/socket.h presence... yes
	checking for sys/socket.h... yes
	checking sys/time.h usability... yes
	checking sys/time.h presence... yes
	checking for sys/time.h... yes
	checking for unistd.h... (cached) yes
	checking for stdbool.h that conforms to C99... yes
	checking for _Bool... yes
	checking for inline... inline
	checking for pid_t... yes
	checking for size_t... (cached) yes
	checking for ssize_t... yes
	checking vfork.h usability... no
	checking vfork.h presence... no
	checking for vfork.h... no
	checking for fork... yes
	checking for vfork... yes
	checking for working fork... yes
	checking for working vfork... (cached) yes
	checking for alarm... yes
	checking for dup2... yes
	checking for floor... yes
	checking for gethostname... yes
	checking for gettimeofday... yes
	checking for inet_ntoa... yes
	checking for memmove... yes
	checking for memset... yes
	checking for pow... yes
	checking for regcomp... yes
	checking for socket... yes
	checking for sqrt... yes
	checking for strcasecmp... yes
	checking for strchr... yes
	checking for strcspn... yes
	checking for strdup... yes
	checking for strerror... yes
	checking for strncasecmp... yes
	checking for strrchr... yes
	checking for strstr... yes
	checking for strtol... yes
	checking for strtoul... yes
	checking for strtoull... yes
	checking whether g++ supports is_default_constructible (used by gmock)... yes
	checking that generated files are newer than configure... done
	configure: creating ./config.status
	config.status: creating Makefile
	config.status: creating include/config.h
	config.status: executing depfiles commands
	Updating include/version.h
	test -z "sipp" || rm -f sipp
	test -z "sipp_unittest" || rm -f sipp_unittest
	test -z "" || rm -f
	rm -f *.o
	rm -f gmock/src/*.o
	rm -f gtest/src/*.o
	rm -f src/*.o
	test -z "sipp_unittest.log" || rm -f sipp_unittest.log
	test -z "sipp_unittest.trs" || rm -f sipp_unittest.trs
	test -z "test-suite.log" || rm -f test-suite.log
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-actions.o -MD -MP -MF src/.deps/sipp-actions.Tpo -c -o src/sipp-actions.o `test -f 'src/actions.cpp' || echo './'`src/actions.cpp
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-auth.o -MD -MP -MF src/.deps/sipp-auth.Tpo -c -o src/sipp-auth.o `test -f 'src/auth.cpp' || echo './'`src/auth.cpp
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-comp.o -MD -MP -MF src/.deps/sipp-comp.Tpo -c -o src/sipp-comp.o `test -f 'src/comp.c' || echo './'`src/comp.c
	mv -f src/.deps/sipp-comp.Tpo src/.deps/sipp-comp.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-call.o -MD -MP -MF src/.deps/sipp-call.Tpo -c -o src/sipp-call.o `test -f 'src/call.cpp' || echo './'`src/call.cpp
	mv -f src/.deps/sipp-actions.Tpo src/.deps/sipp-actions.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-deadcall.o -MD -MP -MF src/.deps/sipp-deadcall.Tpo -c -o src/sipp-deadcall.o `test -f 'src/deadcall.cpp' || echo './'`src/deadcall.cpp
	mv -f src/.deps/sipp-auth.Tpo src/.deps/sipp-auth.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-infile.o -MD -MP -MF src/.deps/sipp-infile.Tpo -c -o src/sipp-infile.o `test -f 'src/infile.cpp' || echo './'`src/infile.cpp
	mv -f src/.deps/sipp-infile.Tpo src/.deps/sipp-infile.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-listener.o -MD -MP -MF src/.deps/sipp-listener.Tpo -c -o src/sipp-listener.o `test -f 'src/listener.cpp' || echo './'`src/listener.cpp
	mv -f src/.deps/sipp-deadcall.Tpo src/.deps/sipp-deadcall.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-logger.o -MD -MP -MF src/.deps/sipp-logger.Tpo -c -o src/sipp-logger.o `test -f 'src/logger.cpp' || echo './'`src/logger.cpp
	mv -f src/.deps/sipp-listener.Tpo src/.deps/sipp-listener.Po
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-md5.o -MD -MP -MF src/.deps/sipp-md5.Tpo -c -o src/sipp-md5.o `test -f 'src/md5.c' || echo './'`src/md5.c
	mv -f src/.deps/sipp-logger.Tpo src/.deps/sipp-logger.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-message.o -MD -MP -MF src/.deps/sipp-message.Tpo -c -o src/sipp-message.o `test -f 'src/message.cpp' || echo './'`src/message.cpp
	mv -f src/.deps/sipp-md5.Tpo src/.deps/sipp-md5.Po
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-milenage.o -MD -MP -MF src/.deps/sipp-milenage.Tpo -c -o src/sipp-milenage.o `test -f 'src/milenage.c' || echo './'`src/milenage.c
	mv -f src/.deps/sipp-call.Tpo src/.deps/sipp-call.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-call_generation_task.o -MD -MP -MF src/.deps/sipp-call_generation_task.Tpo -c -o src/sipp-call_generation_task.o `test -f 'src/call_generation_task.cpp' || echo './'`src/call_generation_task.cpp
	mv -f src/.deps/sipp-milenage.Tpo src/.deps/sipp-milenage.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-ratetask.o -MD -MP -MF src/.deps/sipp-ratetask.Tpo -c -o src/sipp-ratetask.o `test -f 'src/ratetask.cpp' || echo './'`src/ratetask.cpp
	mv -f src/.deps/sipp-call_generation_task.Tpo src/.deps/sipp-call_generation_task.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-reporttask.o -MD -MP -MF src/.deps/sipp-reporttask.Tpo -c -o src/sipp-reporttask.o `test -f 'src/reporttask.cpp' || echo './'`src/reporttask.cpp
	mv -f src/.deps/sipp-ratetask.Tpo src/.deps/sipp-ratetask.Po
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-rijndael.o -MD -MP -MF src/.deps/sipp-rijndael.Tpo -c -o src/sipp-rijndael.o `test -f 'src/rijndael.c' || echo './'`src/rijndael.c
	mv -f src/.deps/sipp-message.Tpo src/.deps/sipp-message.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-scenario.o -MD -MP -MF src/.deps/sipp-scenario.Tpo -c -o src/sipp-scenario.o `test -f 'src/scenario.cpp' || echo './'`src/scenario.cpp
	mv -f src/.deps/sipp-rijndael.Tpo src/.deps/sipp-rijndael.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-sip_parser.o -MD -MP -MF src/.deps/sipp-sip_parser.Tpo -c -o src/sipp-sip_parser.o `test -f 'src/sip_parser.cpp' || echo './'`src/sip_parser.cpp
	mv -f src/.deps/sipp-sip_parser.Tpo src/.deps/sipp-sip_parser.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-screen.o -MD -MP -MF src/.deps/sipp-screen.Tpo -c -o src/sipp-screen.o `test -f 'src/screen.cpp' || echo './'`src/screen.cpp
	mv -f src/.deps/sipp-reporttask.Tpo src/.deps/sipp-reporttask.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-socket.o -MD -MP -MF src/.deps/sipp-socket.Tpo -c -o src/sipp-socket.o `test -f 'src/socket.cpp' || echo './'`src/socket.cpp
	mv -f src/.deps/sipp-screen.Tpo src/.deps/sipp-screen.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-socketowner.o -MD -MP -MF src/.deps/sipp-socketowner.Tpo -c -o src/sipp-socketowner.o `test -f 'src/socketowner.cpp' || echo './'`src/socketowner.cpp
	mv -f src/.deps/sipp-socketowner.Tpo src/.deps/sipp-socketowner.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-stat.o -MD -MP -MF src/.deps/sipp-stat.Tpo -c -o src/sipp-stat.o `test -f 'src/stat.cpp' || echo './'`src/stat.cpp
	mv -f src/.deps/sipp-scenario.Tpo src/.deps/sipp-scenario.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-strings.o -MD -MP -MF src/.deps/sipp-strings.Tpo -c -o src/sipp-strings.o `test -f 'src/strings.cpp' || echo './'`src/strings.cpp
	mv -f src/.deps/sipp-strings.Tpo src/.deps/sipp-strings.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-task.o -MD -MP -MF src/.deps/sipp-task.Tpo -c -o src/sipp-task.o `test -f 'src/task.cpp' || echo './'`src/task.cpp
	mv -f src/.deps/sipp-socket.Tpo src/.deps/sipp-socket.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-time.o -MD -MP -MF src/.deps/sipp-time.Tpo -c -o src/sipp-time.o `test -f 'src/time.cpp' || echo './'`src/time.cpp
	mv -f src/.deps/sipp-task.Tpo src/.deps/sipp-task.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-variables.o -MD -MP -MF src/.deps/sipp-variables.Tpo -c -o src/sipp-variables.o `test -f 'src/variables.cpp' || echo './'`src/variables.cpp
	mv -f src/.deps/sipp-time.Tpo src/.deps/sipp-time.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-watchdog.o -MD -MP -MF src/.deps/sipp-watchdog.Tpo -c -o src/sipp-watchdog.o `test -f 'src/watchdog.cpp' || echo './'`src/watchdog.cpp
	mv -f src/.deps/sipp-watchdog.Tpo src/.deps/sipp-watchdog.Po
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-xp_parser.o -MD -MP -MF src/.deps/sipp-xp_parser.Tpo -c -o src/sipp-xp_parser.o `test -f 'src/xp_parser.c' || echo './'`src/xp_parser.c
	mv -f src/.deps/sipp-xp_parser.Tpo src/.deps/sipp-xp_parser.Po
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-sslinit.o -MD -MP -MF src/.deps/sipp-sslinit.Tpo -c -o src/sipp-sslinit.o `test -f 'src/sslinit.c' || echo './'`src/sslinit.c
	mv -f src/.deps/sipp-variables.Tpo src/.deps/sipp-variables.Po
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-sslthreadsafe.o -MD -MP -MF src/.deps/sipp-sslthreadsafe.Tpo -c -o src/sipp-sslthreadsafe.o `test -f 'src/sslthreadsafe.c' || echo './'`src/sslthreadsafe.c
	mv -f src/.deps/sipp-sslinit.Tpo src/.deps/sipp-sslinit.Po
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-prepare_pcap.o -MD -MP -MF src/.deps/sipp-prepare_pcap.Tpo -c -o src/sipp-prepare_pcap.o `test -f 'src/prepare_pcap.c' || echo './'`src/prepare_pcap.c
	mv -f src/.deps/sipp-sslthreadsafe.Tpo src/.deps/sipp-sslthreadsafe.Po
	gcc -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu11 -D__LINUX -MT src/sipp-send_packets.o -MD -MP -MF src/.deps/sipp-send_packets.Tpo -c -o src/sipp-send_packets.o `test -f 'src/send_packets.c' || echo './'`src/send_packets.c
	mv -f src/.deps/sipp-prepare_pcap.Tpo src/.deps/sipp-prepare_pcap.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-rtpstream.o -MD -MP -MF src/.deps/sipp-rtpstream.Tpo -c -o src/sipp-rtpstream.o `test -f 'src/rtpstream.cpp' || echo './'`src/rtpstream.cpp
	mv -f src/.deps/sipp-send_packets.Tpo src/.deps/sipp-send_packets.Po
	g++ -DHAVE_CONFIG_H -DUSE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP -DHAVE_GSL -DHAVE_EPOLL -I. -I./include   -D__LINUX -I./include -Wall -pedantic  -g -O2 -std=gnu++11 -MT src/sipp-sipp.o -MD -MP -MF src/.deps/sipp-sipp.Tpo -c -o src/sipp-sipp.o `test -f 'src/sipp.cpp' || echo './'`src/sipp.cpp
	mv -f src/.deps/sipp-stat.Tpo src/.deps/sipp-stat.Po
	mv -f src/.deps/sipp-rtpstream.Tpo src/.deps/sipp-rtpstream.Po
	mv -f src/.deps/sipp-sipp.Tpo src/.deps/sipp-sipp.Po
	g++ -I./include -Wall -pedantic  -g -O2 -std=gnu++11   -o sipp src/sipp-actions.o src/sipp-auth.o src/sipp-comp.o src/sipp-call.o src/sipp-deadcall.o src/sipp-infile.o src/sipp-listener.o src/sipp-logger.o src/sipp-md5.o src/sipp-message.o src/sipp-milenage.o src/sipp-call_generation_task.o src/sipp-ratetask.o src/sipp-reporttask.o src/sipp-rijndael.o src/sipp-scenario.o src/sipp-sip_parser.o src/sipp-screen.o src/sipp-socket.o src/sipp-socketowner.o src/sipp-stat.o src/sipp-strings.o src/sipp-task.o src/sipp-time.o src/sipp-variables.o src/sipp-watchdog.o src/sipp-xp_parser.o   src/sipp-sslinit.o src/sipp-sslthreadsafe.o  src/sipp-prepare_pcap.o src/sipp-send_packets.o src/sipp-rtpstream.o src/sipp-sipp.o  -lgslcblas -lm -lpcap -lsctp -lcrypto -lssl -lm -lpthread -ldl -lcurses
	src/sipp-stat.o: In function `CNormal::sample()':
	/root/sipp/src/stat.cpp:1862: undefined reference to `gsl_ran_gaussian'
	src/sipp-stat.o: In function `CNormal::cdfInv(double)':
	/root/sipp/src/stat.cpp:1884: undefined reference to `gsl_cdf_gaussian_Pinv'
	src/sipp-stat.o: In function `CGPareto::sample()':
	/root/sipp/src/stat.cpp:2018: undefined reference to `gsl_ran_flat'
	src/sipp-stat.o: In function `CNegBin::sample()':
	/root/sipp/src/stat.cpp:2088: undefined reference to `gsl_ran_negative_binomial'
	src/sipp-stat.o: In function `gsl_init()':
	/root/sipp/src/stat.cpp:1843: undefined reference to `gsl_rng_env_setup'
	/root/sipp/src/stat.cpp:1844: undefined reference to `gsl_rng_default'
	/root/sipp/src/stat.cpp:1844: undefined reference to `gsl_rng_alloc'
	src/sipp-stat.o: In function `CLogNormal::sample()':
	/root/sipp/src/stat.cpp:1890: undefined reference to `gsl_ran_lognormal'
	src/sipp-stat.o: In function `CLogNormal::cdfInv(double)':
	/root/sipp/src/stat.cpp:1908: undefined reference to `gsl_cdf_lognormal_Pinv'
	src/sipp-stat.o: In function `CExponential::sample()':
	/root/sipp/src/stat.cpp:1920: undefined reference to `gsl_ran_exponential'
	src/sipp-stat.o: In function `CExponential::cdfInv(double)':
	/root/sipp/src/stat.cpp:1936: undefined reference to `gsl_cdf_exponential_Pinv'
	src/sipp-stat.o: In function `CWeibull::sample()':
	/root/sipp/src/stat.cpp:1949: undefined reference to `gsl_ran_weibull'
	src/sipp-stat.o: In function `CWeibull::cdfInv(double)':
	/root/sipp/src/stat.cpp:1970: undefined reference to `gsl_cdf_weibull_Pinv'
	src/sipp-stat.o: In function `CPareto::sample()':
	/root/sipp/src/stat.cpp:1983: undefined reference to `gsl_ran_pareto'
	src/sipp-stat.o: In function `CPareto::cdfInv(double)':
	/root/sipp/src/stat.cpp:2004: undefined reference to `gsl_cdf_pareto_Pinv'
	src/sipp-stat.o: In function `CGamma::sample()':
	/root/sipp/src/stat.cpp:2054: undefined reference to `gsl_ran_gamma'
	src/sipp-stat.o: In function `CGamma::cdfInv(double)':
	/root/sipp/src/stat.cpp:2075: undefined reference to `gsl_cdf_gamma_Pinv'
	collect2: error: ld returned 1 exit status
	Makefile:971: recipe for target 'sipp' failed
	make: *** [sipp] Error 1

**Comment by leonroy** [comment]
Actually, just noticed I needed `pkg-config` which  (correct me if wrong) seems to have linked the gsl libs and resolved the issue.

**Comment by linuxmaniac** [comment]
same here, using ``pkg-config`` solved the undefined reference errors

**Comment by xlhan** [comment]
When I was compiling 3.6.0 release (centos 7), I got below error:
fatal error: gsl/gsl_rng.h: No such file or directory
 #include <gsl/gsl_rng.h>
                         ^
compilation terminated.

I did "yum install gsl-devel" and solved the compile issue successfully.
