### ISSUE TITLE
Realloc bug

### ISSUE THREAD

**Issue by rkday** [SIPp/sipp#28]
SIPped, the Polycom fork of SIPp (https://github.com/SIPp/polycom-sipped) fixes up a realloc bug. It would be good to get this merged into the main SIPp code.

It looks as though the relevant commit is f68a9c5.

**Comment by wdoekes** [comment]
The mentioned code does not seem to exist in master.

The problematic code was introduced in SIPped itself:
https://github.com/SIPp/polycom-sipped/commit/de2ea4ca753d56cc5be1ba1739df47cc3ddd0254
