### ISSUE TITLE
[sipp] which has secret

### ISSUE THREAD

**Issue by ramin-git** [SIPp/sipp#292]
I can successfully stress test with sip account [sipp]. But how can test with [sipp] (sip user) which has secret (password) ?

**Comment by wdoekes** [comment]
I'm not sure what you're saying.

Do you mean the `-s` and `-ap` options? See the `sipp -help` texts.

**Comment by ramin-git** [comment]
what do you mean with -ap?
-ap is a sip secret or not?

**Comment by wdoekes** [comment]
I still don't know what you mean. But you haven't bothered to find out what I meant.

Check the `sipp -help` and if that doesn't help you, you'll need to try harder to explain what you mean.

```
$ sipp -help | grep -C2 -- -ap
```
```
   -au              : Set authorization username for authentication challenges. Default is taken
                      from -s argument
   -ap              : Set the password for authentication challenges. Default is 'password'
   -s               : Set the username part of the request URI. Default is 'service'.
   -default_behaviors: Set the default behaviors that SIPp will use.  Possible values are:
```

**Comment by wdoekes** [comment]
You're welcome!
