### ISSUE TITLE
Migrate official doc to readthedocs.io, make SF docs oboslete

### ISSUE THREAD

**Issue by nshopik** [SIPp/sipp#307]
My last(final) changes on documentation didn't appear on http://sipp-wip.readthedocs.io, is readdocs no longer pull docs from repo?

**Comment by wdoekes** [comment]
I triggered a manual build now, so all updates should be live now. Please confirm.

There can only be one webhook, and it's attached to sipp.rtd, not sipp-wip.rtd.
If @rkday could set up sipp.readthedocs.io to build the master branch, we'd get auto-builds.
*friendly poke* :)

Obviously it'd be nice if some of the new docs from the docs branch got merged into master too, but I haven't found any time to look at that.

**Comment by nshopik** [comment]
All looks good now. yeah it would be nice to have sipp.readthedocs.io as main docs

> Obviously it'd be nice if some of the new docs from the docs branch got merged into master too, but I haven't found any time to look at that.

What docs branch? On main repo there only `documentation` branch which contains @rkday initial attempt to convert to rst which we already done.

Shouldn't we mark SF docs as legacy, so people come to newer version at readdocs?

**Comment by wdoekes** [comment]
> What docs branch? On main repo there only documentation branch which contains @rkday initial attempt to convert to rst which we already done.

I thought it might actually contain new docs. But perhaps it does not. Unsure :)

> Shouldn't we mark SF docs as legacy, so people come to newer version at readdocs?

Yes, but only when it has a proper (non-WIP) url.

**Comment by nshopik** [comment]
I leave this issue open to keep track of progress

**Comment by wdoekes** [comment]
URL is updated since rtfd/readthedocs.org#5824.

Closing!
