### ISSUE TITLE
Use RapidXML for XML parsing

### ISSUE THREAD

**Issue by rkday** [SIPp/sipp#31]
Rather than the occasionally buggy custom XML parser SIPp currently uses, we should investigate moving to RapidXML (http://rapidxml.sourceforge.net/).

**Comment by rkday** [comment]
As RapidXML hasn't been updated since 2009, this is probably not sensible.

**Comment by lemenkov** [comment]
We'd better to reuse some proven and popular XML library but certainly not this one.
