### ISSUE TITLE
sipp-3.5.0 error : Automatic response mode for an unexpected INFO, NOTIFY, OPTIONS or UPDATE for call

### ISSUE THREAD

**Issue by jennytrinh17** [SIPp/sipp#316]
I'm still getting error when executing the call using sipp command below.

Last error : Automatic response mode for an unexpected INFO, NOTIFY, OPTIONS or UPDATE for call in the log file

even though I used the -aa options to enable automatic 200 response to info, notify, options, update messages. 
I'm stuck and not sure how to fix `this.`

I attach my xml file and csv input file. here is my sipp command where i'm using asterisk SIP server at address 172.21.1.102:

./sipp 172.21.1.102 -i 172.21.1.88 -t -t1 -sf REGISTER_INVITE_client_mod.xml -inf register_asterisk_client1.csv -aa -m 1 -l 1 trace_msg -trace_err

`

[sipp.zip](https://github.com/SIPp/sipp/files/1096758/sipp.zip)

**Comment by rkday** [comment]
This shouldn't be an error - we should find a better way to display this, like incrementing and displaying a counter.
