### ISSUE TITLE
[Question] Default message handler during pause in XML scenario

### ISSUE THREAD

**Issue by annoviko** [SIPp/sipp#327]
Hello,

I've got a following problem. I need to have a pause in my XML scenario and during this pause I am receiving UPDATE messages that should be handled (just to sent 200 OK at least). I have looked though documentation http://sipp-wip.readthedocs.io/en/latest/scenarios/actions.html - but haven't found the answer to my question. Is there any way to set default handler for some SIP messages? Because, currently my scenarios are failed during pause due to UPDATE. 

```xml
<!--- may receive UPDATE during this action --->
<pause milliseconds="5000"/>
```

**Comment by wdoekes** [comment]
Does the `-aa` option help?

**Comment by wdoekes** [comment]
No feedback after N days.
