### ISSUE TITLE
sipp is not working on FreeBSD 11.0 and 10.3

### ISSUE THREAD

**Issue by tsgan** [SIPp/sipp#331]
I know sipp was working on FreeBSD 9.x before and now I'm trying to use sipp (SIPp v3.5.1-TLS-RTPSTREAM) on FreeBSD 11.0-RELEASE-p9, but it is not working anymore. It gives me:

2018-01-12	12:29:15.529546	1515731355.529546: Unknown RTP address 'addr not supported'.

and someone is already reported here:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=222764

How can we solve this issue?

**Comment by tsgan** [comment]
SIPp v3.3 (TLS, built Jul 22 2013, 08:43:48) works for me, but this package is old and built for FreeBSD 9.x.
How can we fix this issue for newer version of sipp?

**Comment by tsgan** [comment]
SIPp v3.4.1 is the last version that works. SIPp v3.5.0 is not working and v3.6-dev is not working too.

**Comment by tsgan** [comment]
It seems like get_inet_address() function is not working anymore in case of FreeBSD.
Following old function from sipp-3.4.1 in sipp-3.5.0 sort of works for me:
```
--- src/socket.cpp-orig 2018-01-12 14:36:14.758860000 +0800
+++ src/socket.cpp      2018-01-12 15:31:55.925119000 +0800
@@ -337,11 +337,27 @@

 static char* get_inet_address(const struct sockaddr_storage* addr, char* dst, int len)
 {
-    if (getnameinfo(_RCAST(struct sockaddr*, addr), sizeof(*addr),
-                    dst, len, NULL, 0, NI_NUMERICHOST) != 0) {
-        snprintf(dst, len, "addr not supported");
+//    if (getnameinfo(_RCAST(struct sockaddr*, addr), sizeof(*addr),
+//                    dst, len, NULL, 0, NI_NUMERICHOST) != 0) {
+//        snprintf(dst, len, "addr not supported");
+//    }
+//    return dst;
+    static char * ip_addr = NULL;
+
+    if (!ip_addr) {
+        ip_addr = (char *)malloc(1024*sizeof(char));
+    }
+    if (getnameinfo(_RCAST(struct sockaddr *, addr),
+                    SOCK_ADDR_SIZE(addr),
+                    ip_addr,
+                    1024,
+                    NULL,
+                    0,
+                    NI_NUMERICHOST) != 0) {
+        strcpy(ip_addr, "addr not supported");
     }
-    return dst;
+
+    return ip_addr;
 }
```

I had to run following command to make it work in this case:
```
sipp -sn uac -m 1 -d 30000 -r 10 -l 200 -s 1002 -mp 6000 SERVER_IP -l 10 -trace_err -i MY_IP -mi MY_IP -rsa SERVER_IP:5060 -auth_uri SERVER_IP:5060
```

**Comment by wdoekes** [comment]
@tsgan : Can you check behaviour on 3.6-dev (master branch)?

**Comment by tsgan** [comment]
I will try to test it in couple of days, thanks a lot.

**Comment by wdoekes** [comment]
Assuming this has been fixed..
