### ISSUE TITLE
ereg action search_in attribute is not precise enough

### ISSUE THREAD

**Issue by jimbojd72** [SIPp/sipp#342]
I got a strange case in one of my test case where the header that sipp has matched was not expected.

My scenario tried to match on the `f:` header from below, but since the header was in non-compact form (From:), it didn't find it (which may be explainable). The problem is the fact that it has match on another header, `X-ref:` instead, which was not as expected. 

`search_in` attribute should prevent this behaviour (only exactly matching) or add a way to provide a regexp as parameter to be more specific about one or multiple headers found. This could lead to a test that become unexpectedly passing or failing. 

Sipp relevant scenario section:
```
<recv request="INVITE" crlf="true" rrs="true">
        <action>
            <!-- Check that it uses the extension name provided in UAC-->
            <ereg regexp="Overriden Contact Name" search_in="hdr" header="f:" assign_to="whole_uri" check_it="true" />
        </action>
    </recv>
<Reference variables="whole_uri" />
```

INVITE under test:
```
INVITE sip:AOR@172.20.0.2:58718;x-ebcid=AjbxnZ7lXgA SIP/2.0
Record-Route: <sip:MS0xMC4xMTcuMjQ4LjI0Ni01MDYw@199.87.123.10:5061;lr>
Via: SIP/2.0/UDP 10.0.0.10:5061;branch=hdakjshdjksahdah;rport;x-sc
Via: SIP/2.0/UDP 10.25.248.246:5060;rport;branch=dlkasdaskda-ePFwDGqS48G
Via: SIP/2.0/UDP 10.25.242.131:5060;received=10.117.242.131;branch=z9hG4bK2f6d5de1
Max-Forwards: 69
From: "Overriden Contact Name" <sip:1001@reg.myip.net>;tag=as5ad68920
To: <sip:AOR@v1.test>
Contact: <sip:1001@10.117.242.131:5060>
Call-ID: 1ae20fdd4544ac4f601451df3f9f754b
CSeq: 102 INVITE
Date: Fri, 20 Apr 2018 21:03:51 GMT
Allow: INVITE, ACK, CANCEL, OPTIONS, BYE, REFER, SUBSCRIBE, NOTIFY, INFO, PUBLISH, MESSAGE
Supported: replaces
X-ref: test-1-16@172.20.0.2
Privacy: none
Content-Type: application/sdp
Content-Length: 340
Session-ID: 0ed51f8c00bf915c2fe171cb0672fee8dasda

v=0
o=root 460362372 460362372 IN IP4 10.25.123.204
c=IN IP4 10.25.123.200
t=0 0
m=audio 25958 RTP/AVP 0 9 3 8 18 101
a=rtpmap:18 G729/8000
a=fmtp:18 annexb=no
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-16
a=ptime:20
a=sendrecv
```

Sipp error message:
```
Failed regexp match: looking in ' test-1-16@172.20.0.2', with regexp 'Overriden Contact Name'."
```

thanks

**Comment by wdoekes** [comment]
You're probably interested in this hidden bit of documentation:
https://github.com/SIPp/sipp/commit/da85ff66#diff-9b3b62c53c75be6c2617495d9469f6abR23

Can also be seen in the original docs:
http://sipp.sourceforge.net/doc/reference.html#Regular+expressions

**Comment by jimbojd72** [comment]
My bad on that. Sorry for bothering.

Thanks for your quick feedback.
