### ISSUE TITLE
Inject custom empty keyword into message

### ISSUE THREAD

**Issue by IvanRibakov** [SIPp/sipp#364]
At the moment if I add custom blank keyword to my scenario using `-key KEYWORD ''`, when injected in SIP message (via `[KEYWORD]`), it is still rendered as `''` (similar for double quotes). Command-line construct like `-key KEYWORD` (no value passed at all) seems to break parameter parsing (juding by error messages that I've seen).

Is there a way to define an empty keyword, such that when injected in a SIP message it is rendered without quotes?

**Comment by wdoekes** [comment]
```
X-Keyword: -[keyword]-
```
with `-key keyword ''` becomes:
```
X-Keyword: --
```
So. Cannot reproduce.
