### ISSUE TITLE
can not play RTP if not logged in as root

### ISSUE THREAD

**Issue by stadelmannj** [SIPp/sipp#368]
if I'm trying to play RTP when logged with a normal user, i get the following error:
Can't create raw IPv4 socket (need to run as root?): Operation not permitted.
and scenario stops.

SIPp is called with this command 
sipp 192.168.2.8 -sf uac-hold.xml -m 1 -s +41993500670 -i 10.254.156.97 -mi 10.254.156.97 -t t1

anybody any idee how to fix this ?

**Comment by wdoekes** [comment]
Yes. You need CAP_NET_RAW capabilities for raw sockets when using pcap-replay.

See also #57 and #369.

You can do rtpstream without root though.
