### ISSUE TITLE
play pcap: it works well in windows 10 but it does not works in windows 10's subsystem(ubuntu 16.04)

### ISSUE THREAD

**Issue by joeonly** [SIPp/sipp#369]
simple scenario works well but failed to play pcap in windows 10's subsystem.
it says:
2018-11-06      01:54:17.626934 1541440457.626934: Can't create raw IPv4 socket (need to run as root?): Protocol not supported.

I am sure that I run it as root user.

**Comment by joeonly** [comment]
Years ago I ran my samples in windows with Cygwin. For study, it usually worked well.

But now I want to run them in windows 10's subsystem, just like I run them in Linux because I need to prepare only one script(shell) file this way. And to show sipp in windows is easy than other OSs in some case, eg. to call with a sip phone. So I really need the ability to run it in win10's subsystem.

**Comment by wdoekes** [comment]
I'm sorry. This is not something I'm willing to spend time on.

If you figure out why windows doesn't do raw sockets, feel free to elaborate and someone might come up with a patch.

Note that we don't really need raw sockets at all, but it's a bigger change to make it work without.
