### ISSUE TITLE
Xml for scripts? really?

### ISSUE THREAD

**Issue by heretic13** [SIPp/sipp#377]
Hello.

Are you seriously suggesting writing complex script logic in xml?
Are you aware that languages like lua, javascript or python are commonly used to write scripts?

Why waste people's time learning the special xml syntax, while they can spend it on some set of lua functions and accomplish the same task? Abstract people will better understand high-level language than specialized xml.

**Comment by wdoekes** [comment]
Hi!

I appreciate the time you've taken to submit feedback. However, it is not in the right format.

You should either:
- take op parchment and ink and write the original HP authors back in 2003 a nice handwritten letter; or
- submit a pull request with the changes needed so we can deprecate xml.

Closing for now.
