### ISSUE TITLE
NOP not getting executed in scenario

### ISSUE THREAD

**Issue by amoonrah** [SIPp/sipp#378]
[wsm_out.txt](https://github.com/SIPp/sipp/files/2677946/wsm_out.txt)

I want to send a PRACK if 180 or 183 have an Rseq header, the regex work, I logged it in a message and I see the variables getting set, however the NOP inside the recv block is not getting executed.

running sipp 3.5.2, centos 7, 

attached scenario as text

**Comment by amoonrah** [comment]
figured it out ... please disregard

**Comment by amoonrah** [comment]
did it this way 

 
  <recv response="180" optional="true"  next="prack" test="v_100rel">
    <action>
      <ereg regexp="(.*)100rel(.*)" search_in="hdr" header="Require: " assign_to="v_100rel" />
      <ereg regexp=".*" search_in="hdr" header="RSeq: " assign_to="v_rseq"/>
      <ereg regexp=".*" search_in="hdr" header="CSeq: " assign_to="v_cseq"/>
    </action>
  </recv>

**Comment by stadelmannj** [comment]
can you share your final, working scenario please ?

**Comment by amoonrah** [comment]
sure ... I've attached the final document.

[wsm.txt](https://github.com/SIPp/sipp/files/2684481/wsm.txt)

**Comment by stadelmannj** [comment]
Hi Amoonrah,
with your final solution attached, prack is also send if Require: 100rel is not in 18x response. i.e. the next="prack" statement is executed irrespective of the test="v_100rel.

any idea why ?

**Comment by amoonrah** [comment]
I'll have to check on this, it's been a while since I've looked at it
