### ISSUE TITLE
sipp no valid Call-ID: header in reply

### ISSUE THREAD

**Issue by ilyinvv** [SIPp/sipp#380]
Good day!
I tested the sipp through opensips, the dialogue module is opened on the opensips which creates a CallId of the form DLG_, when a package containing such CallId is received, sipp logs the following:
No valid Call-ID: header in reply
I tested sipp with other UA they all work well with CallId opensips
Below is the call log
[uac_auth2REF_24262_errors.log](https://github.com/SIPp/sipp/files/2810952/uac_auth2REF_24262_errors.log)

**Comment by wdoekes** [comment]
What I can tell you, is that the packet is wrong:
```
$ cat -A uac_auth2REF_24262_errors.log  | head -n20
sipp: The following events occured:$
2019-01-30^I09:51:25.100701^I1548823885.100701: (1) No valid Call-ID: header in reply 'INVITE sip:3136439102@85.12.197.169:5065 SIP/2.0^M$
Via: SIP/2.0/UDP 85.12.253.12:5060;branch=z9hG4bK831a.2bb3de85.0^M$
From: "3136439104" <sip:104@sbc.profintel.ru>;tag=b62e0d72-be14-4d3c-bd6a-b4da593b6b17^M$
To: <sip:3136439102@sbc2.profintel.ru>$

^-- look, no CR ("^M") here

Contact: <sip:85.12.253.12;did=a19.a2e590e>^M$
Call-ID: DLGCH_K0IEXzVwYzJiQlwKMGRkMX5GSAxiKmJ+exQADWYsZ2QsFQFb^M$
CSeq: 6476 INVITE^M$
Allow: OPTIONS, REGISTER, SUBSCRIBE, NOTIFY, PUBLISH, INVITE, ACK, BYE, CANCEL, UPDATE, PRACK, MESSAGE, REFER^M$
Supported: 100rel, timer, replaces, norefersub^M$
Session-Expires: 1800^M$
Min-SE: 90^M$
Max-Forwards: 70^M$
Content-Type: application/sdp^M$
Content-Length: 278^M$
^M$
```
Although that doesn't explain it not finding the Call-ID at all.
