### ISSUE TITLE
Solaris build failure with 3.5.2

### ISSUE THREAD

**Issue by sjthomason** [SIPp/sipp#387]
Solaris doesn't have `struct iphdr`
```prepare_pcap.c:248:27: error: dereferencing pointer to incomplete type 'struct iphdr'```

Look like this fixed in #232 but is only in master and not in 3.5.  Can this be backported?

**Comment by wdoekes** [comment]
#232 removes iphdr. So if it's broken in 3.5, I suspect it's also broken in master: did you test that?

I don't have an opensolaris to test this on. I'm parking this for someone to volunteer. Pull requests are welcome.

**Comment by sjthomason** [comment]
@wdoekes We're using master successfully on Solaris 11.3 and 11.4.  If you'd like, just close this pending the 3.6 release.

Thanks!

**Comment by wdoekes** [comment]
:ok_hand:
