### ISSUE TITLE
'Discarding message which can't be mapped to a known SIPp call' when UAC recieves INVITE message

### ISSUE THREAD

**Issue by ann43** [SIPp/sipp#392]
Hi, I use SIPp v3.5.2 for my testing. My scenario as below:
A-party          My device            B-party                         UAS(as media-server)
 ------------->INVITE
100 Trying <-------
200 OK<-----------
--------------> ACK
                              -------------------------------------->interact with UAS
                              ------------> INVITE(B)
========================================================
I start one SIPp client as A-party, local ip: : 
./sipp 169.254.192.1:5060 -sn uac -trace_msg -trace_err -sf uac.xml -m 1

I start one SIPp server as B-party: 
 ./sipp -sn uas -trace_msg -trace_err -nr -sf Bparty.xml

I start one SIPp server as media-server:
./sipp 169.254.192.1:5061 -sn uas -trace_msg -trace_err -nr -sf uas.xml

A-party send INVITE message:
INVITE sip:9133@169.254.192.1:5060 SIP/2.0^M
Via: SIP/2.0/UDP 169.254.192.7:5060;branch=z9hG4bK-692-1-0^M
From: 356799892980 <sip:356799892980@169.254.192.7:5060>;tag=692SIPpTag001^M
To: 9133 <sip:9133@169.254.192.1:5060>^M
Call-ID: 1-692@169.254.192.7^M
CSeq: 1 INVITE^M
Contact: sip:356799892980@169.254.192.7:5060^M
Max-Forwards: 70^M
Subject: Performance Test^M
Content-Type: application/sdp^M
Content-Length:   137^M
^M
v=0^M
o=user1 53655765 2353687637 IN IP4 169.254.192.7^M
s=-^M
c=IN IP4 169.254.192.7^M
t=0 0^M
m=audio 6000 RTP/AVP 0^M
a=rtpmap:0 PCMU/8000^M
--------------------------------------------------------------------------------

INVITE(B) message:
INVITE sip:008801711506236@169.254.192.7:5060 SIP/2.0^M
Via: SIP/2.0/UDP 135.242.106.246:5060;branch=z9hG4bK302a^M
To: sip:008801711506236@169.254.192.7^M
From: sip:356799892980@169.254.192.1:5060;tag=1^M
Call-ID: 7bd3ee7b540a471c@ABC-0-0-1^M
CSeq: 1 INVITE^M
Max-Forwards: 70^M
Accept: application/sdp^M
Allow: INVITE, ACK, CANCEL, BYE, INFO, UPDATE, MESSAGE, NOTIFY^M
User-Agent: SIP^M
Supported: timer^M
Content-Length: 0^M

My issue:  INVITE(B) message always receives by A-party, and report error 'Discarding message which can't be mapped to a known SIPp call'. SIPp supports such scenarios? Thanks!

**Comment by kamilosz** [comment]
Hi,

on the begining You have to use sf or sn parameter when You calling sipp, not together.

As I see A start on 169.x.x.7,
and B start on 169.x.x.1.

If these are standard build-in scenarios it doesn’t run.

Kamil

**Comment by wdoekes** [comment]
Thanks @kamilosz .

This fixes things, yes? @ann43 

Closing..
