### ISSUE TITLE
Add my own XML scenarios problem

### ISSUE THREAD

**Issue by zhaozhenhong5** [SIPp/sipp#393]
Hello, I tried to add my XML,the code you can see [here](https://github.com/zhaozhenhong5/zhao/blob/master/sipp_uac_register.xml). And sent command “./sipp -sn uac 192.168.110.10 -sf sipp_uac_register.xml” . But it shown fail that : "No injection file was specified!" . Do someone know why?

**Comment by hagbard-c** [comment]
hi zhaozhenhong5

in your xml u use the "field"-variable:
> From: "sipp" <sip:[field0]@cc.qiyukf.com>;tag=[call_number]

this variable can only be used if u are injecting values from an external csv file.
for more infos: [SIPp reference documentation - Injecting values from an external CSV during calls](https://sipp-wip.readthedocs.io/en/latest/scenarios/inject_from_csv.html)

But in your sipp-command u dont specify an csv file via the "-inf" parameter.

**Comment by wdoekes** [comment]
Thanks @hagbard-c .

@zhaozhenhong5 : I assume this fixes things. Closing.

**Comment by zhaozhenhong5** [comment]
yes,thank you
