### ISSUE TITLE
Ruby test harness

### ISSUE THREAD

**Issue by rkday** [SIPp/sipp#4]
SIPped, the Polycom fork of SIPp (https://github.com/SIPp/polycom-sipped) has a Ruby test harness that can be used to drive SIPp and provide regression testing. It would be good to get this merged into the main SIPp code.

It looks as though the relevant commits are 89b5049, 89b5049, c63a904, e4d066d, 4955dec, 13588ce, fd4b38a, aae26fb, 7613269, ae0c8c4, 2d4086e, d7cf829, bc538bd, f38926b, 324d4e0, 28316f8, d060afe, 78b55d8, d087c8c, 165cdfe, 69c83e6, b335a2d, 9909784, 1db1b71, 47d9eef, e542254, c026762, 9860f4f, 0b68d95, 801707f, 2e09034, df9b28a, 1d0294d, 938b50c, 954985d, 298669d, 94f13e0, 4ce98bb, c56e5e4, 723ab5a, 2326a97, 3589a39, f54e544, 3745aa4, a04b599, 9756227, d945d10 and 670b001, though some of these relate to Ruby tests for other features not yet merged.

There are also a set of commits relating to making the test harness run on Windows - these are 7dbdc72, 2d857ce, a64364c, 9e01953, e5edfab, e8588a5 and 68bd8c9.

**Comment by wdoekes** [comment]
Not doing this.
