### ISSUE TITLE
Sending ACK to a different remote address

### ISSUE THREAD

**Issue by Maratk1n** [SIPp/sipp#418]
I am trying to reproduce the following scenario
```
# 5060        5089        5181
#  |  INVITE   |           |
#  |---------->|  INVITE   |
#  |           |---------->|
#  |           |180 Ringing|
#  |           |<----------|
#  |           |  200 OK   |
#  |           |<----------|
#  |180 Ringing|           |
#  |<----------|           |
#  |  200 OK   |           |
#  |<----------|           |
#  |         ACK           |
#  |---------------------->|
#  |         BYE           |
#  |---------------------->|
#  |         200 OK        |
#  |<----------------------|
```
Port 5060 is SIPp client, 5089 -- proxy, 5181 -- server.
Command for start scenario:
```
sipp "127.0.0.1:5181" -i 127.0.0.1 -p 5060 -sf SimpleUAC.xml -inf ${TEST_AUTH_INFO} -s "18885555555*100" -rsa 127.0.0.1:5089 \
                        -timeout 5 -timeout_error -nd -m 1
```
_SimpleUAC.xml_:
```
<?xml version="1.0" encoding="ISO-8859-1" ?>
<!DOCTYPE scenario SYSTEM "sipp.dtd">

<scenario name="SimpleUAC">
 <pause distribution="uniform" min="0" max="600"/> 
<send>
<![CDATA[
INVITE sip:[service]@[remote_ip]:[remote_port] SIP/2.0
Via: SIP/2.0/[transport] [local_ip]:[local_port];branch=[branch];rport
From: <sip:[field0]@[remote_ip]:[remote_port]>;tag=[pid]SIPpTag00[call_number]
To: <sip:[service]@[remote_ip]:[remote_port]>
Call-ID: [call_id]
CSeq: [cseq] INVITE
Contact: sip:[service]@[local_ip]:[local_port]
Max-Forwards: 70
User-Agent: [sipp_version]
Content-Type: application/sdp
Content-Length: [len]

v=0
o=151 9655 9655 IN IP4 10.135.0.12
s=-
c=IN IP4 10.135.0.12
t=0 0
m=audio 50024 RTP/AVP 8 0 2 18
a=rtpmap:8 PCMA/8000
a=rtpmap:0 PCMU/8000
a=rtpmap:2 G726-32/8000/1
a=rtpmap:18 G729/8000
a=ptime:20
a=maxptime:80
a=sendrecv
a=rtcp:50025
]]>
</send>

<recv response="100" optional="true"/>
<recv response="180" optional="true"/>
<recv response="183" optional="true"/>
<recv response="200" rrs="true"/>
 
<send>
<![CDATA[
ACK [next_url] SIP/2.0
[last_Via:]
[last_From:]
[last_To:]
[last_Call-ID:]
[last_CSeq:]
Max-Forwards: 70
Content-Length: [len]
]]>

</send>
<pause milliseconds="1000"/>
<send retrans="500">
<![CDATA[
BYE [next_url] SIP/2.0
[last_Via:]
[last_To:]
[last_From:]
[last_Call-ID:]
CSeq: [cseq+2] BYE
Contact: sip:[service]@[local_ip]:[local_port]
Content-Length: [len]
]]>
</send>

<recv response="100" optional="true"/>
<recv response="200"/>
</scenario>
```
but I get this result:
```
# 5060        5089        5181
#  |  INVITE   |           |
#  |---------->|  INVITE   |
#  |           |---------->|
#  |           |180 Ringing|
#  |           |<----------|
#  |           |  200 OK   |
#  |           |<----------|
#  |180 Ringing|           |
#  |<----------|           |
#  |  200 OK   |           |
#  |<----------|           |
#  |  ACK      |           |
#  |---------->|  ACK      |
#  |           |---------->|
#  |  BYE      |           |
#  |---------->|  BYE      |
#  |           |---------->|
#  |           |  200 OK   |
#  |           |<----------|
#  |  200 OK   |           |
#  |<----------|           |
```
How I can solve it?

**Comment by Maratk1n** [comment]
`200 OK` response:
```
2019/10/15 17:19:46.590876 127.0.0.1:5089 -> 127.0.0.1:5060
SIP/2.0 200 OK
Via: SIP/2.0/UDP 127.0.0.1:5060;received=127.0.0.1;branch=z9hG4bK-6167-1-1;rport=5060
From: <sip:18885555555*100@127.0.0.1:5181>;tag=6167SIPpTag001
To: <sip:18885555555*100@127.0.0.1:5181>;tag=73194dfdf1873e275b145a764c4dbbfe.eabe
Call-ID: 1-6167@127.0.0.1
CSeq: 1 INVITE
Contact: <sip:127.0.0.1:5181>
Server: kamailio (5.1.1 (x86_64/linux))
Content-Length: 0
```

**Comment by sergey-safarov** [comment]
Thinks apps on 127.0.0.1:5089 injects Record-Route header

**Comment by Maratk1n** [comment]
> Thinks apps on 127.0.0.1:5089 injects Record-Route header

No. I sent an example of 200 OK (180 Ringing the same) of response from 5089 to 5060.

**Comment by Maratk1n** [comment]
Packet capture if you need
[flow.txt](https://github.com/SIPp/sipp/files/3734693/flow.txt)

**Comment by rkday** [comment]
@Maratk1n - I think you want to use `setdest` to change where the ACK gets sent. See the example at https://sipp.readthedocs.io/en/latest/scenarios/actions.html#setdest.

**Comment by Maratk1n** [comment]
> @Maratk1n - I think you want to use `setdest` to change where the ACK gets sent. See the example at https://sipp.readthedocs.io/en/latest/scenarios/actions.html#setdest.

Great! Thank you.
It solved my problem.
```
<nop>
  <action>
    <setdest host="[remote_ip]" port="[remote_port]" protocol="[transport]" />
  </action>
</nop>
```

**Comment by medOualla** [comment]
@Maratk1n have you done these lines both in UAC and UAS?
UAS before receiving the ACK, filling the address from contact header of the INVITE, the same as for UAC, filling details from the contact of 200ok?

**Comment by Maratk1n** [comment]
@medOualla , I put this lines in UAC side. As I remember I used Kamailio, not SIPp, as UAS.

**Comment by medOualla** [comment]
@Maratk1n Ah I see. In my setup, I'm using SIPp as both the caller (192.168.33.2:5080) and the callee (192.168.33.4:5060), with Kamailio acting as the SIP proxy (192.168.33.3:5060) in between.

Here are my observations:
  When using the [next_url] in subsequent requests in the caller script ("uac.xml"), the R-URI of the callee is included because the caller receives the contact address from the callee in the 200 OK of the INVIE and stores it in its route set. However, SIPp always sends the subsequent requests to Kamailio.
  Applying the solution discussed here resolved the issue on the caller's side, allowing it to send subsequent requests like ACK and BYE to the callee's address (192.168.33.4).
  While the callee receives these requests, it doesn’t seem to understand or act on them and keeps retransmitting the 200 OK "because it thinks that it doesn't received an ACK yet". Therefore, it should use the **setdest** values for **_host_**, **_port_**, and **_transport_** after sending the 200 OK of the INVITE.

This fixed my issue, but I am curious to know if I did it correctly or if there's a better approach?
