### ISSUE TITLE
Sipp fork new process

### ISSUE THREAD

**Issue by kypopthuk1996** [SIPp/sipp#419]
Hello dev team!
Is there any way to get sipp to fork a new process?
if so, in which part of your code to look.

**Comment by ttiimmoonn** [comment]
Yes, the question is interesting: for example, it would be cool when you set up a media session to start another program for generating or analyzing media traffic

**Comment by rkday** [comment]
Yes, we do - something like the following:

```
    <action>
      <exec command="sleep 0.2" />
    </action>
  </recv>
```

See https://sipp.readthedocs.io/en/v3.6.0/scenarios/actions.html#external-commands for the docs. #423 adds an `<exec verify>` action which can check the return code.

**Comment by kypopthuk1996** [comment]
And I can somehow handle the result of executing third-party code?
Is there any way to save the execution code to a variable?
