### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by Linson93** [SIPp/sipp#427]
first ,I use command autiogen.sh
second ,I use command  configure
third ,I use build.sh  --with-pcap --with-sctp --with-openssl
 
then there is something wrong in my system 
//------------------------------------------------
./include/version.h:3:2: error: #error "  This is a stub version.h. You should not use this fake version number, but a git-tagged version instead.     You should download the proper .tar.gz which includes a proper version.h or clone the SIPp repository using git."
 #error "\
  ^~~~~
In file included from src/sipp.cpp:58:0:
./include/version.h:3:2: error: #error "  This is a stub version.h. You should not use this fake version number, but a git-tagged version instead.     You should download the proper .tar.gz which includes a proper version.h or clone the SIPp repository using git."
 #error "\
  ^~~~~
//-----------------------------------------------
how can I buid sucessully? I need u help ,thank u very much

**Comment by wdoekes** [comment]
@Linson93 : it's really frustrating to have to answer this. You have failed to read the error message which includes everything you need to know. Sad times.
