### ISSUE TITLE
pcap_play is not working in master branch on FreeBSD 11.2

### ISSUE THREAD

**Issue by kadabusha** [SIPp/sipp#433]
uac_pcap works just fine in sipp 3.3.

1. Build sipp
```
[sipp@freebsd /var/tmp]$ git clone https://github.com/SIPp/sipp.git
[sipp@freebsd /var/tmp]$ cd sipp
[sipp@freebsd /var/tmp/sipp]$ cmake . -DUSE_SSL=1 -DUSE_SCTP=1 -DUSE_PCAP=1 -DUSE_GSL=1 -DUSE_EPOLL=1
```
2. Run UAS, could be at no media:
```
[sipp@freebsd /var/tmp/sipp]$ sudo ./sipp -sn uas -i 127.0.0.1 -p 5060
```
3. Run UAC using built-in uac_pcap scenario:
```
[sipp@freebsd /var/tmp/sipp]$ sudo ./sipp 127.0.0.1:5060 -sn uac_pcap -p 5061 -m 1
```

### Current behavior:
```
2019-10-28      16:43:20.806096 1572281000.806096: Can't bind media raw socket
```

Split from [issue #426](https://github.com/SIPp/sipp/issues/426#issuecomment-549061838)

**Comment by rkday** [comment]
Thanks - given the report that this worked in older versions, I did a bit more digging.

https://github.com/SIPp/sipp/pull/434 should fix it, by not trying to bind to a particular port. Can you pull and test that?

(By the way, I think https://github.com/SIPp/sipp/commit/a929d1ad77c27877384f9a6f5bc16d0573b2624e broke it.)

**Comment by kadabusha** [comment]
Hi, @rkday - I did the steps listed below, no error with "raw socket" was noticed, the media steam seems to be sent to/from proper ports, as well as the media is playable from packet dump [pcap_play.zip](https://github.com/SIPp/sipp/files/3801864/pcap_play.zip)

At least from my side I did not notice any issues with pcap_play for the time being, it finally worked as a charm to me!
```
[sipp@freebsd /var/tmp]$ rm -rf sipp
[sipp@freebsd /var/tmp]$ git clone https://github.com/SIPp/sipp.git
[sipp@freebsd /var/tmp]$ cd sipp
[sipp@freebsd /var/tmp]$ git checkout fix_freebsd_raw_sockets
[sipp@freebsd /var/tmp]$ cmake . -DUSE_EPOLL= -DUSE_PCAP=1
[sipp@freebsd /var/tmp]$ make
[sipp@freebsd /var/tmp/sipp]$ sudo ./sipp -sn uas -i 192.168.0.159 -mi 192.168.0.159 -p 5060 -rtp_echo -mp 5080
[sipp@freebsd /var/tmp/sipp]$ sudo tcpdump -i lo0 -vvv udp portrange 5060-5090 and host 127.0.0.1 -w /var/tmp/pcap_play.pcap
[sipp@freebsd /var/tmp/sipp]$ sudo ./sipp 127.0.0.1:5060 -sn uac_pcap -i 127.0.0.1 -mi 127.0.0.1 -p 5061 -mp 5071 -m 1
```

**Comment by rkday** [comment]
Thanks! I've merged that - I'm closing this issue, but do comment/reopen if I've missed something.
