### ISSUE TITLE
Can't install/build SIPP on Ubuntu 18.04 "sys/endian.h and le16toh - not found"

### ISSUE THREAD

**Issue by TamerL** [SIPp/sipp#436]
Hi All,
I got this error after cloning the repository:

ThinkPad-X1-Carbon-6th:~/sipp$ cmake .
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for endian.h
-- Looking for endian.h - found
-- Looking for sys/endian.h
-- Looking for sys/endian.h - not found
-- Looking for sys/epoll.h
-- Looking for sys/epoll.h - found
-- Performing Test HAVE_UDP_UH_PREFIX
-- Performing Test HAVE_UDP_UH_PREFIX - Success
-- Looking for le16toh
-- Looking for le16toh - found
-- Looking for le16toh
-- Looking for le16toh - not found
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURSES_LIBRARY
    linked by target "sipp_unittest" in directory ~/sipp
    linked by target "sipp" in directory ~/sipp

-- Configuring incomplete, errors occurred!
See also "~/sipp/CMakeFiles/CMakeOutput.log".
See also "~/sipp/CMakeFiles/CMakeError.log".

**Comment by wdoekes** [comment]
```
sudo apt-get install libncurses-dev
```
I'll agree that that error is not real pretty though.

**Comment by TamerL** [comment]
Thank You :+1:
