### ISSUE TITLE
Add support for a cfg file instead of cli arguments

### ISSUE THREAD

**Issue by ctradu** [SIPp/sipp#44]
Instead of cli arguments we should support all those options in a cfg file

Ex: 
```
sipp -c scenario.cfg 
``` 
versus
```
sipp -sf scenario.xml -inf scenario.csv  sut.hostname.me -mp 1234 -i 10.11.12.13 -t u1  -p 1232 -r 10 -m 200 -l 15 -aa
```

The format of the cfg file may be yaml, json or something else.
This can be added to work in parallel with the current mode.

**Comment by wdoekes** [comment]
Closing for now. If someone is interesting in creating this, we can certainly reopen.
