### ISSUE TITLE
Switch from UDP to TCP over 1300 bytes

### ISSUE THREAD

**Issue by kiskele** [SIPp/sipp#444]
Hi

Sipp should be able to follow RFC 3261:

   If a request is within 200 bytes of the path MTU, or if it is larger
   than 1300 bytes and the path MTU is unknown, the request MUST be sent
   using an RFC 2914 [43] congestion controlled transport protocol, such
   as TCP. If this causes a change in the transport protocol from the
   one indicated in the top Via, the value in the top Via MUST be
   changed.  This prevents fragmentation of messages over UDP and
   provides congestion control for larger messages.  However,
   implementations MUST be able to handle messages up to the maximum
   datagram packet size.  For UDP, this size is 65,535 bytes, including
   IP and UDP headers.

Thanks!

BR,
Tamas

**Comment by kriptasz** [comment]
This feature would be epic.

**Comment by wdoekes** [comment]
I see why you would want this, but this is not something that's easy to implement, nor is it useful for all circumstances. (We want to be able to test non-standard stuff.) Sorry.
