### ISSUE TITLE
Session ID allocation upon constructing SDP

### ISSUE THREAD

**Issue by kadabusha** [SIPp/sipp#446]
An issue I faced with session ID parameter of SDP - as far as I could understand RFC 4566 and RFC 3264, it is unique identified for the session, allocated by creation tool, that should also satisfy uniqueness of this parameter for each SDP constructed.
The only way to get session ID randomized that is known to me is to use CSV file with values for it, though for thousands and millions of calls it's not too convenient.

Maybe there is another way to get it achieved? Got some issues with softswitch that requires uniqueness for session id in UAS scenario in particular when different UAS are on same IP but on own ports. That way <nettype>, <addrtype>, and <unicast-address> are the same, while sess-id and sess-version are hardcoded static values, e.g. 

```
o=user1 53655765 2353687637 IN IP4 192.168.0.132
```

RFC excerpts:
```   
<sess-id> is a numeric string such that the tuple of <username>,
<sess-id>, <nettype>, <addrtype>, and <unicast-address> forms a
globally unique identifier for the session.  The method of
<sess-id> allocation is up to the creating tool, but it has been
suggested that a Network Time Protocol (NTP) format timestamp be
used to ensure uniqueness [13].
```
https://tools.ietf.org/html/rfc4566#section-5.2

```
The numeric value of the session id
   and version in the o line MUST be representable with a 64 bit signed
   integer.  The initial value of the version MUST be less than
   (2**62)-1, to avoid rollovers.
```
https://tools.ietf.org/html/rfc3264#section-5

```
The session ID in the origin field
MUST be unique for each SDP constructed to indicate media
capabilities.
```
https://tools.ietf.org/html/rfc3264#section-9

**Comment by wdoekes** [comment]
There are various fields you could use.

Instead of:
```
o=user1 53655765 2353687637
```
you could do:
```
o=user1 536557[call_number] 23536876[call_number] 
```
