### ISSUE TITLE
What determines the value of SSRC?

### ISSUE THREAD

**Issue by hmoghani** [SIPp/sipp#455]
Hi,

I have an issue with my SIPp rtp streams. I'm working with a third party application that uses the RTP streams generated by sipp and makes decision based on the SSRC. The issue is both UAS and UAC generates the same SSRC in my case and as a result the third party application can not do its job correctly. Is it possible for me to change the SSRC in my xml file? or somehow make it random in the code and recompile it?

I couldn't find much in the code about how SSRC is determined. I'd appreciate if anyone could help me with this issue.

Thanks,

**Comment by mwasiel** [comment]
I believe it uses what's in the pcap so you can send two pcaps, however,
it's super easy to modify the sipp code to make the ssrc configurable. I
remember doing that exact thing at oracle.

**Comment by hmoghani** [comment]
Thanks @mwasiel. The sources are wave files, so I don't know if it can be changed.
