### ISSUE TITLE
XML attribute values are not consistently unescaped (e.g. for <strcmp value>)

### ISSUE THREAD

**Issue by nud** [SIPp/sipp#458]
Most XML attributes are not unescaped by the XML parser. After checking the source code it looks like only `<ereg>` is.

While it has no practical consequences most of the time, it makes it impossible to e.g. use `<strcmp>` to do something like this:

```xml
  <strcmp
      assign_to="result"
      variable="strvar"
      value="&#34;Some User&#34; &lt;sip:foo@bar.com&gt;"
      />
```
I suppose solving https://github.com/SIPp/sipp/issues/31 would fix the problem globally, but in the meantime unescaping at least attributes that are meant to contain strings would be a nice improvement.

**Comment by wdoekes** [comment]
Thanks @nud !
