### ISSUE TITLE
Generating PCAP files

### ISSUE THREAD

**Issue by Strongbyte-SD** [SIPp/sipp#461]
SIPp comes with out of band (RFC 2833) DTMFs in the pcap/ directory but not for letters A, B, C and D. How can i generate these myself ?

**Comment by DomMartin27** [comment]
If you are using version 3.6.0 there is a method to send DTMF without needing the pcap files:
[https://github.com/SIPp/sipp/releases/tag/v3.6.0](https://github.com/SIPp/sipp/releases/tag/v3.6.0)
There are instructions on that page on how to do this.

Or if you wanted to generate them yourself, you can capture a pcap trace of those digits during a call and then filter & export each digit you want using wireshark.

**Comment by wdoekes** [comment]
Not a bug :)
