### ISSUE TITLE
Need informations about how the console work

### ISSUE THREAD

**Issue by Qlenglet** [SIPp/sipp#468]
Hi everybody,

I need to use SIPp in my project but I have some issues with the console when you play a scenario. I need to execute a new instance of SIPp but with a build-in SSH client in Node-JS. So I use a plugin to send SSH request and get back the information about the SIPp instance launched with this pugin. My first frame from the output of the command is fine but then I have many issue with the next frame, which are not the reporting screen but only the value which change with some coordinates.
I will attach two screenshot of what information I have when I try to display the output of the command.

First capture : 
![Screenshot_20200806_134636](https://user-images.githubusercontent.com/33154036/89528645-ac867200-d7eb-11ea-91e9-19838e724716.png)

Second:
![Screenshot_20200806_134656](https://user-images.githubusercontent.com/33154036/89528695-c1630580-d7eb-11ea-857a-dd0b65b4a2b2.png)

Can somebody explain me how the output works during the execution of a scenario (or someone have an idea)? It will help me a lot for my development 

Thanks you for your time and cooperation

Lenglet Quentin

**Comment by wdoekes** [comment]
Try starting `sipp` with `TERM=dumb` in the environment.

**Comment by Qlenglet** [comment]
Sadly, It give me nothing as output (like nohing is happened). I am on the last revisions of the code.
I could take a lot of time to understand how this output works but my project is due to the end of the month, so It's a little bit complicated.

Thanks anyway, Il make some tests to

**Comment by wdoekes** [comment]
Sounds like your ssh plugin is smarter than you want.

Compare:
```
$ ssh localhost sipp -m 1 -sn uac 1.2.3.4 | cat -A
walter@localhost's password: 
Resolving remote host '1.2.3.4'... Done.
------------------------------ Scenario Screen -------- [1-9]: Change Screen --^M$
  Call-rate(length)   Port   Total-time  Total-calls  Remote-host^M$
```
^- normal output, because the terminal is deemed to be really dumb

And with `ssh -t`:
```
$ ssh -t localhost sipp -m 1 -sn uac 1.2.3.4 | cat -A
walter@localhost's password: 
Resolving remote host '1.2.3.4'... Done.$
                                         ^[[2J^[[2J$
                                                    $
                                                     $
...
^[[?1049h^[[22;0;0t^[[1;73r^[(B^[[m^[[4l^[[?7h^[[73;1H^[[?1049l^[[23;0;0t^M^[[?1l^[>------------------------------ Scenario Screen -------
```
^- fancier terminal capabilities

Maybe you can convince your ssh to provide a dumber terminal. Possibly by piping the output to `cat`.

**Comment by Qlenglet** [comment]
Ok thanks I will look If I can make this work with my libraries
I will keep you posted about my progress

**Comment by Qlenglet** [comment]
I found a workaround to use a terminal emulator on the client side. Thank you for your help and have a good day !
