### ISSUE TITLE
Prepare release 3.6.1 -- feedback on bugs/issues required

### ISSUE THREAD

**Issue by wdoekes** [SIPp/sipp#482]
I think there are about 30 commits since 3.6.0, so it's about time for a 3.6.1.

Are there any outstanding (severe) bugs / missing features that should go in?

**Comment by lemenkov** [comment]
No objections. So let's release it!

**Comment by wdoekes** [comment]
:+1: 

It is released.

@rkday: do you want to do a docker-built static-binary upload somewhere?
