### ISSUE TITLE
SIPp 3.3 discarding 200 OK response

### ISSUE THREAD

**Issue by Murali6205** [SIPp/sipp#494]
I am using SIPp to place a call to an Avaya CM station. The invite goes fine and server is responding back with 100, 180 and 200 responses, but when validating 200 OK, it throws following error

--------------------------------Error on console-----------------------------------------------------------------------------------------
2020-10-09      09:38:46:486    1602216526.486507: Discarding message which can't be mapped to a known SIPp call:
SIP/2.0 200 OK
From: <sip:sipp@162.17.9.24>;tag=jWGvVNFeh-SIPP1
To: <sip:40027@107.14.186.60>;tag=0106935cd19eb1ed6a5ed1535900
Call-ID: SIPP1
CSeq: 20 INVITE
Via: SIP/2.0/TCP 162.17.9.24:5060;branch=z9hG4bK-SIPP1
Supported: histinfo,join,replaces,sdp-anat,timer
Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,SUBSCRIBE,NOTIFY,REFER,INFO,PRACK,PUBLISH
Contact: <sip:107.14.186.60;transport=tcp>
Accept-Language: en
Record-Route: <sip:107.14.186.60;transport=tcp;lr>
Server: Avaya CM/R016x.00.0.345.0
Session-Expires: 3000;refresher=uas
Content-Type: application/sdp
Content-Length:   167

v=0
o=- 1 2 IN IP4 107.14.186.60
s=-
c=IN IP4 107.14.186.65
b=AS:64
t=0 0
m=audio 2584 RTP/AVP 0 101
a=rtpmap:0 PCMU/8000
a=rtpmap:101 telephone-event/8000
-------------------------------------------Error end-----------------------------------------
--------------------------------------UAC Script content for invite and receive response----------------------------------------------
<?xml version="1.0" encoding="ISO-8859-1" ?>
<scenario name="Basic">

<send>
 <![CDATA[
INVITE sip:40027@107.14.186.60:5060;transport=tcp SIP/2.0
From: <sip:sipp@162.17.9.24>;tag=jWGvVNFeh-SIPP1
To: sip:40027@107.14.186.60
CSeq: 20 INVITE
Via: SIP/2.0/TCP 162.17.9.24:5060;branch=z9hG4bK-SIPP1;rport
Call-ID: SIPP1
Max-Forwards: 70
Supported: replaces, outbound
Session-Expires: 3000;refresher=uas
Allow: INVITE, ACK, CANCEL, BYE
User-to-User: 04C80431303030
Contact: <sip:sipp@162.17.9.24:3372;transport=tcp>
Content-Length: 316

v=0
o=libsip 1420002944 1420002945 IN IP4 162.17.9.24
s=Talk
c=IN IP4 162.17.9.24
t=0 0
m=audio 7078 RTP/AVP 111 110 0 8 101
a=rtpmap:111 speex/16000
a=fmtp:111 vbr=on
a=rtpmap:110 speex/8000
a=fmtp:110 vbr=on
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-11
 ]]>
 </send>

<recv response="100" optional="true">
</recv>
<recv response="180" optional="true">
</recv>
<recv response="200">
</recv>
--------------------------------------UAC Script content for invite and receive response----------------------------------------------
----------------------------------------Generated log file contents------------------------------------------------
----------------------------------------------- 2020-10-09 09:32:04:282.346
TCP message sent (775 bytes):

INVITE sip:40027@107.14.186.60:5060;transport=tcp SIP/2.0
From: <sip:sipp@162.17.9.24>;tag=jWGvVNFeh-SIPP1
To: sip:40027@107.14.186.60
CSeq: 20 INVITE
Via: SIP/2.0/TCP 162.17.9.24:5060;branch=z9hG4bK-SIPP1;rport
Call-ID: SIPP1
Max-Forwards: 70
Supported: replaces, outbound
Session-Expires: 3000;refresher=uas
Allow: INVITE, ACK, CANCEL, BYE
User-to-User: 04C80431303030
Contact: <sip:sipp@162.17.9.24:3372;transport=tcp>
Content-Length: 316

v=0
o=libsip 1420002944 1420002945 IN IP4 162.17.9.24
s=Talk
c=IN IP4 162.17.9.24
t=0 0
m=audio 7078 RTP/AVP 111 110 0 8 101
a=rtpmap:111 speex/16000
a=fmtp:111 vbr=on
a=rtpmap:110 speex/8000
a=fmtp:110 vbr=on
a=rtpmap:0 PCMU/8000
a=rtpmap:8 PCMA/8000
a=rtpmap:101 telephone-event/8000
a=fmtp:101 0-11

----------------------------------------------- 2020-10-09 09:32:04:296.617
TCP message received [251] bytes :

SIP/2.0 100 Trying
From: <sip:sipp@162.17.9.24>;tag=jWGvVNFeh-SIPP1
To: <sip:40027@107.14.186.60>
Call-ID: SIPP1
CSeq: 20 INVITE
Via: SIP/2.0/TCP 162.17.9.24:5060;branch=z9hG4bK-SIPP1
Server: Avaya CM/R016x.00.0.345.0
Content-Length:     0

----------------------------------------------- 2020-10-09 09:32:04:300.580
TCP message received [535] bytes :

SIP/2.0 180 Ringing
From: <sip:sipp@162.17.9.24>;tag=jWGvVNFeh-SIPP1
To: <sip:40027@107.14.186.60>;tag=80e8fd46cc19eb1e26a5ed1535900
Call-ID: SIPP1
CSeq: 20 INVITE
Via: SIP/2.0/TCP 162.17.9.24:5060;branch=z9hG4bK-SIPP1
Supported: histinfo,join,replaces,sdp-anat,timer
Allow: INVITE,ACK,OPTIONS,BYE,CANCEL,SUBSCRIBE,NOTIFY,REFER,INFO,PRACK,PUBLISH
Contact: <sip:107.14.186.60;transport=tcp>
Accept-Language: en
Record-Route: <sip:107.14.186.60;transport=tcp;lr>
Server: Avaya CM/R016x.00.0.345.0
Content-Length:     0
----------------------------------------Generated log file contents------------------------------------------------

**Comment by wdoekes** [comment]
I won't be supporting SIPp 3.3. Please upgrade before filing any bug reports,

**Comment by Murali6205** [comment]
I have upgraded to 3.6.0, but still facing same issue

**Comment by Murali6205** [comment]
Should i open this as a new issue?
