### ISSUE TITLE
version.h: No such file or directory

### ISSUE THREAD

**Issue by poplongjiu** [SIPp/sipp#500]
Hi
I'm trying to build sipp on Linux
but I get this error:
make
[  0%] Built target version
[  3%] Building CXX object CMakeFiles/sipp.dir/src/call.cpp.o
/root/sipp-3.6.1/src/call.cpp:62:21: fatal error: version.h: No such file or directory
 #include "version.h"
                     ^
compilation terminated.
make[2]: *** [CMakeFiles/sipp.dir/src/call.cpp.o] Error 1
make[1]: *** [CMakeFiles/sipp.dir/all] Error 2
make: *** [all] Error 2

I can't find the version.h in the include.

I sincerely desire for your help.

**Comment by wdoekes** [comment]
```
$ wget 'https://github.com/SIPp/sipp/releases/download/v3.6.1/sipp-3.6.1.tar.gz'
$ tar zxf sipp-3.6.1.tar.gz 
$ cd sipp-3.6.1/
$ ./build.sh --full
$ ./sipp -v
SIPp v3.6.1-TLS-SCTP-PCAP-RTPSTREAM.
```

**Comment by wdoekes** [comment]
Apparently 3.6.1 doesn't have this commit, apparently.

https://github.com/SIPp/sipp/commit/55a1286a6c6170c0fd6fc92997caa7a1032df144

But searching for "version.h" would've turned up enough info.
