### ISSUE TITLE
SRTP question

### ISSUE THREAD

**Issue by smititelu** [SIPp/sipp#510]
Hi,

My question is: Does SIPp currently supports generate/echo secure RTP? If yes, can you give a tip on how to configure/use it?

I've compiles latest sipp sources in my attempt to try the SRTP support added here: b2f7d2a

I've configured UAC to send RTP with:
```
      <exec rtp_stream="apattern,1,0,PCMU/8000" />
```
and SDP crypto params like this:
```
      a=crypto:[cryptotag1audio] [cryptosuiteaescm128sha1321audio] inline:[cryptokeyparams1audio]
      a=crypto:[cryptotag2audio] [cryptosuiteaescm128sha1802audio] inline:[cryptokeyparams2audio]
```

I've configured UAS to echo RTP with
```
      <exec rtp_echo="startaudio,0,PCMU/8000" />
```
and SDP crypto params like this:
```
      a=crypto:[cryptotag1audio] [cryptosuiteaescm128sha1321audio] inline:[cryptokeyparams1audio]
```

I can see SDP crypto keys generated and sent. However, RTP sent/echoed is still plain RTP.

Thank you,
Stefan

**Comment by aakver** [comment]
Hi @smititelu , I am newbie for SIPp, so far I have installed SIPP-3.6.1 (as per https://github.com/SIPp/sipp/releases/tag/v3.6.1) and also able to get rtp/udp/tls calls working. But I was searching for exactly how to get SIPP work for TLS/SRTP , can you help me with launch commands ? especially how to use "srtpcheck_debug , debugrefileaudio and processIncomingPacket() and processOutgoingPacket()" as I dont see these options in sipp launch CLI !
