### ISSUE TITLE
Github action build-static doesn't produce a static build

### ISSUE THREAD

**Issue by negbie** [SIPp/sipp#514]
I've tried the build-static action from @rkday but the produced binary isn't static:

ldd sipp
	linux-vdso.so.1 (0x00007ffef1198000)
	libgsl.so.23 => not found
	libgslcblas.so.0 => not found
	libpcap.so.1 => not found
	libstdc++.so.6 => /lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007fa20ac35000)
	libc.musl-x86_64.so.1 => not found
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fa20aae6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fa20a8f2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fa20b0fc000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007fa20a8d7000)

**Comment by wdoekes** [comment]
Yes. I noticed this as well.

I don't use these, so I'd rather remove support than waste time fixing it. @rkday ?

**Comment by rkday** [comment]
I don't actually use them any more either, but I think #614 has fixed.

**Comment by negbie** [comment]
Thanks!
