### ISSUE TITLE
Allow ereg to omit assign_to

### ISSUE THREAD

**Issue by opticron** [SIPp/sipp#52]
The regex matching in SIPp should be allowed to omit assign_to if check_it or check_it_inverse are set. Requiring assign_to to be present in these circumstances presents an annoyance since checking the value of the match beyond the regex itself is often unnecessary and the single variable reference must then be resolved.

**Comment by fadimko** [comment]
#312 
made assign_to optional if check_it or check_it_inverse are set for tags 'test' and 'strcmp' in this pr

**Comment by wdoekes** [comment]
Fixed by #312.
