### ISSUE TITLE
Continuous registration as UAS to an IP-PBX to accept incoming calls at any time

### ISSUE THREAD

**Issue by Palezvar** [SIPp/sipp#545]
I have been playing with sipp for a week now and I was wondering if sipp has support for refreshing its own registration with an IP-PBX when running in UAS mode. Our goal is to keep the sipp-UAS record in the SIP registrar table so that we can call it from a UAC at any time we want.

I cannot think of a scenario xml file that both registers periodically and keep the system running to accept incoming calls arbitrarily.

Thanks,

**Comment by wdoekes** [comment]
> I cannot think of a scenario xml file that both registers periodically and keep the system running to accept incoming calls arbitrarily.

Me neither. It might be possible, or it might not. I have no quick answers for you here.

**Comment by Palezvar** [comment]
Thank you for all the answers. We will keep testing with different scenarios and update the ticket if we are successful.
