### ISSUE TITLE
Cannot play pcaps with sipp-3.7.0.rc1

### ISSUE THREAD

**Issue by Palezvar** [SIPp/sipp#564]
I just downloaded sipp-3.7.0.rc1.tar.gz and compiled it with --full option.

Trying to run a local test using the following two commands from the build directory:
1) ./sipp -sn uas
2) ./sipp docs/uac_pcap.xml -l 1 -m 1 -r 1 127.0.0.1

                                 Messages  Retrans   Timeout   Unexpected-Msg
0 :      INVITE ---------->         368       0         0
1 :         100 <----------         0         0         0         0
2 :         180 <----------         368       0         0         0
3 :         183 <----------         0         0         0         0
4 :         200 <----------  E-RTD1 368       0         0         0
5 :         ACK ---------->         368       0
6 :       Pause [      0ms]         368                           0
7 :         BYE ---------->         368       0         0
8 :         200 <----------         368       0         0         0

That default scenario has a couple of pauses and two pcaps to play but the output does not reflect that.

The signaling part is completed successfully but the UAC is not playing back the pcap g711a.pcap and dtmf_2833_1.pcap. I am trying to verify these via tcpdump. I am not seeing any RTP exchange. It does not follow any pause rules either.

am I missing anything?

Thanks,

**Comment by Palezvar** [comment]
I just removed all the pcap related sections from the default uac_pcap.xml and only left a 8000 msec pause in there.

When I run the test locally: ./sipp docs/uac_pcap.xml 127.0.0.1

the pause stage read 0msec. I tried the same thing with the default uac.xml file and added a 8000msec pause and it again shows 0msec pause.

**Comment by wdoekes** [comment]
You're not running `docs/uac_pcap.xml`; you have no `-sf`.

You're running `-sn uac`, which has a pause of 0ms:
```
$ ./sipp -sd uac | grep pause
  <pause/>
```

**Comment by wdoekes** [comment]
I think you'd benefit from something like this:
```patch
--- a/src/sipp.cpp
+++ b/src/sipp.cpp
@@ -1377,10 +1377,16 @@ int main(int argc, char *argv[])
 #define CHECK_PASS() if (option->pass != pass) { break; }
 
     for (int pass = 0; pass <= 3; pass++) {
+       int have_remote_host = 0;
+
         for(argi = 1; argi < argc; argi++) {
             struct sipp_option *option = find_option(argv[argi]);
             if (!option) {
                 if (argv[argi][0] != '-') {
+                    if (have_remote_host) {
+                        ERROR("remote_host argument already supplied.\n");
+                    }
+                    have_remote_host = 1;
                     strncpy(remote_host, argv[argi], sizeof(remote_host) - 1);
                     continue;
                 }
```

**Comment by Palezvar** [comment]
Thank you. I can't believe I missed that.
