### ISSUE TITLE
Any chance of a --variable subject="TestCase 42" to the SIPp commandline?

### ISSUE THREAD

**Issue by TheQue42** [SIPp/sipp#578]
Hi, and thanks for keeping the SIPp software alive.

I hope I havent messed up and not properly read the documentation, but I cant find a way to inject a single _static_ variable into a SIPp run. In a way, just another instance of the -s parameter, that sets the `[service]` field.

I know about the .csv inputs etc, but since I am after a single static value, that is the _same_ for all calls (for that run, it might change the next run), using injection-files seems somewhat messy, and the logic for taking a simple parameter from CLI seems fairly uncomplicated to add, backward compliant, etc.

If someone can give me pointers on where the changes would be needed, I could even give it a try myself, but my first attempt at wrapping my head around the codebase failed somewhat...

**Comment by TheQue42** [comment]
What the.... okey, and I thought I really checked the help-printout for suitable parameters.... Now, I can see that there is even I -variable to set global variables!!
Better get my eyes checked out....I must have been reading only on https://sipp.readthedocs.io/en/v3.6.1/scenarios/actions.html#variable-manipulation.

It wouldnt hurt if there was a more easy-to-find explanation of each parameter, och the read-the-docs page....but maybe I'm just blind there as well :-/

**Comment by rkday** [comment]
Looks like this is resolved. `sipp -h` also has parameter details.
