### ISSUE TITLE
Adjust default UAS scenario to copy received RR to 200OK

### ISSUE THREAD

**Issue by kadabusha** [SIPp/sipp#585]
RFC3261 states:
`When a UAS responds to a request with a response that establishes a
   dialog (such as a 2xx to INVITE), the UAS MUST copy all Record-Route
   header field values from the request into the response (including the
   URIs, URI parameters, and any Record-Route header field parameters,
   whether they are known or unknown to the UAS) and MUST maintain the
   order of those values.`

PR for the change:
https://github.com/SIPp/sipp/pull/584

**Comment by wdoekes** [comment]
Merged. Thanks!
