### ISSUE TITLE
Unsupported keyword 'auto_media_port' in xml scenario file

### ISSUE THREAD

**Issue by weifjsky** [SIPp/sipp#627]
in version 3.7.0 (commit f9a4ba6), the sdp contains the [auto_media_port] parameter, prompting: "Unsupported keyword 'auto_media_port' in xml scenario file"

**Comment by wdoekes** [comment]
The sdp _does not_ contain that keyword.

The changelog _does_ contain that keyword:
```
Features added in 3.7.0~rc1
...
* Removed `-mp` in favor of `-min_rtp_port` and `-max_rtp_port`. Also
  removed `[auto_media_port]`. There are way too many (conflicting)
  options to specify ports here.
```

**Comment by agentgoblin** [comment]
Try [3.7.3](https://github.com/SIPp/sipp/releases/tag/v3.7.3) because changelog for 3.7.3 says:
> Recover -mp and [auto_media_port] by @orgads in https://github.com/SIPp/sipp/pull/653

At least `-mp` now work for my old scenarios.
