### ISSUE TITLE
Unable to remote control sipp 3.7 

### ISSUE THREAD

**Issue by tomasek** [SIPp/sipp#629]
good evening.
I am updating from sipp 3.5.1 to the latest and cannot interact with sipp via netcat nor with the /dev/udp interface (as described on the docs.
It is working as expected on 3.6.0.

**Comment by tomasek** [comment]
As can be seen here, this first image was taken on fedora 37 and with sipp 3.6.0 and the default port for remote control is listening.
![image](https://user-images.githubusercontent.com/1883190/230742665-f74c040d-57a7-43c2-8fd5-6428b3056961.png)

with fedora rawhide and sipp 3.7, the port for remote control is not there.
![image](https://user-images.githubusercontent.com/1883190/230742679-bc353d86-7c54-40aa-8075-d7973231498f.png)

**Comment by rkday** [comment]
Fixed by https://github.com/SIPp/sipp/pull/636.
