### ISSUE TITLE
How to send comfort noise or make sipp read and send the comfort noise from pcap file ?

### ISSUE THREAD

**Issue by Costallat** [SIPp/sipp#632]
Hi all,

I'm trying to reproduce a problem here using sipp to send the same packets(pcap) where we saw the problem. I already made it read the pcap file and send the packets, I can hear the RTP stream(audio), but we think that what is causing the problem is two comfort noise packets that are being sent by the server, but I saw that sipp is not sending those packet, it only sends the 'audio' RTP packets. 

I'm trying to check the code here to see if there is any kind of filter to get only RTP packets with specific payload type where I can add the comfort noise payload so sipp can send them.

Does anybody have any clue or tips where I can check for that? Or if there is another way to generate those comfort noise packets?

Thanks

**Comment by lemenkov** [comment]
PR #687 was merged so it should work now.
