### ISSUE TITLE
Building sipp 3.7.0

### ISSUE THREAD

**Issue by tom10422** [SIPp/sipp#637]
the build.sh wants "sipp-3.7.0/gtest/googletest/src/gtest-all.cc" and the sipp tar gz doesn't seem to have it,  This is on centos 7.   I did a yum install gtest which seemed to work.   Any suggestions?

**Comment by rkday** [comment]
Try with 3.7.1 - should be fixed!

**Comment by tom10422** [comment]
Thank you.   I had to install some sort of network library (can't remember which one), but was able to get it to work.   


-----Original Message-----
