### ISSUE TITLE
compatible with PJSIP

### ISSUE THREAD

**Issue by rionio** [SIPp/sipp#674]
Is this compatible with PJSIP? I want to test different channels that use PJSIP, and also evaluate the audio quality.

**Comment by TheQue42** [comment]
Its compatible with *SIP*. The result depends on what kind of call scenarios _you_ create, but (imho) it's focus is SIP **_signalling_**, and even though there are some mechanisms for playing media/rtp via pcaps (https://sipp.readthedocs.io/en/v3.6.1/scenarios/actions.html#media-rtp-commands),  its not made for audio quality stuff...
