### ISSUE TITLE
Reference documentation is not in the source?

### ISSUE THREAD

**Issue by wdoekes** [SIPp/sipp#69]
http://sipp.sourceforge.net/doc/reference.html should probably be included in the source so it can be updated when behaviour changes.

**Comment by rkday** [comment]
(I've started http://sipp.readthedocs.org/en/latest/index.html, which currently builds off the 'documentation' branch of the SIPp repository - though there's still a bit of work to move all the tables out of http://sipp.sourceforge.net/doc/reference.html into ReStructured Text files.)

**Comment by wdoekes** [comment]
Nice!
