### ISSUE TITLE
Is there a way to enable TLS 1.3 on SIPP version 3.7.2 ?

### ISSUE THREAD

**Issue by othomas-dev** [SIPp/sipp#693]
Hello, 

Is there a way to enable TLS 1.3 on SIPP version 3.7.2 ?
I do not see the version 1.3 in the list of possible versions:
   -tls_version     : Set the TLS protocol version to use (1.0, 1.1, 1.2) -- default is autonegotiate

Thanks a lot, 
Regards,
Olivier

**Comment by orgads** [comment]
Thanks for reporting. I pushed PR #695 to fix that. Will wait for reviews.
