### ISSUE TITLE
/usr/bin/pager: No such file or directory

### ISSUE THREAD

**Issue by ryandesign** [SIPp/sipp#711]
After compiling the latest code in master on macOS, running `./sipp` produced this error:

```
/usr/bin/pager: No such file or directory
```

followed by several pages of usage information.

There is no `pager` on macOS. There are, of course, `less` and `more`.

**Comment by wdoekes** [comment]
Bah. I was hoping to avoid having to add multiple options there, assuming that pager was ubiquitous.

We'd have to add multiple options here then:
```c
    if (!argv[0]) {
        argv[0] = pager; /* missing PAGER */
```
Moving the `access()` call up to check for each possibility and then simply bailing without (p)error if none are found.
