### ISSUE TITLE
Question regarding removing new lines from error messages

### ISSUE THREAD

**Issue by mstovenour** [SIPp/sipp#722]
I noticed that in the 3.6 time frame all the new lines were removed from error logs.  I'm just curious if the result below was the intended outcome or if there is additional work needed to add those back in somewhere else, like in the ERROR() function?

Maybe this was in preparation for adding more logging formats like json or xml?

The below is three separate error messages on one line with no record marker:
```
admin@ip-172-40-1-123:~$ more *errors.log
The following events occurred:
2024-04-20      14:53:31.573796 1713642811.573796: Cannot record route set if there is no Contact2024-04-20     14:53:31.574960 1713642811.574960: Failed regexp match: looking in ';▒W', with regexp 'sip:.*@([0-9A-Za-z\.]+):([0-9]+)'2024-04-20  14:53:31.577092 1713642811.577092: Unknown transport for setdest: ''
```

I could help to finish this work if there is a description somewhere of the intended functionality.

**Comment by orgads** [comment]
@mstovenour Thanks for the report. Can you check if #723 fixes that for you?

**Comment by mstovenour** [comment]
That is working here. Thanks!

Now to fix those errors its spitting out :( [next_url] is getting garbage when the contact header is not in the sip message with rrs="true". Probably sending my own pull request for this one...
