### ISSUE TITLE
sipp 3.4 is not able to run in background mode 

### ISSUE THREAD

**Issue by ardatekin** [SIPp/sipp#73]
I have successfully compiled sipp-3.4 on centos 6.5.

When I run my sipp server scenario in background mode, sipp writes error log and stops running in background.

cd test/
/usr/local/src/sipp-3.4.0/sipp 10.254.4.181 -sf scenario_uas.xml -i 10.254.4.181 -p 6000 -trace_err -trace_logs -bg

Error message in scenario_uas_5033_errors.log file

sipp: The following events occured:
2014-05-21 06:13:41.928328 1400660021.928328: Failed to add FD to epoll, errno = 1 (Operation not permitted

I have verified that this error is also exists in sipp-3.3.990 source.
But sipp 3.2 works perfect in bg.

Running sipp in bg mode is quite important when automating client and server scenarios in shell scripts.
Hence I believe this bug needs to be fixed urgently to use the most stable sipp version in load and performance tests.

Kind Regards,
Arda Tekin

**Comment by aneeshk25** [comment]
May I know which is  the latest build? I checked 3.4.1 and the code changes are not there.

**Comment by wdoekes** [comment]
@aneeshk25: Rob writes here [1] that it may be time for a new release soon. The releases haven't been frequent.

[1] https://github.com/SIPp/sipp/pull/119#issuecomment-70743378

**Comment by aneeshk25** [comment]
Is there any patch or work around for this? So that I can use it till the new release come.

**Comment by wdoekes** [comment]
The workaround would be to use the git `master` branch.

**Comment by aneeshk25** [comment]
I tried with master branch. But I couldn't build it. Thanks for your help in advance.

Following are the errors I got,

> ./build.sh
fatal: Not a git repository (or any of the parent directories): .git

Then I tried with out git, then make failed.

> make sipp_unittest
g++ -DHAVE_CONFIG_H -D_USE_OPENSSL -DPCAPPLAY -DRTP_STREAM -DUSE_SCTP  -DHAVE_EPOLL -I. -I./include  -I./include -D__LINUX  -DGTEST=1 -I./gtest/include -I./gtest  -g -O2 -MT src/sipp_unittest-actions.o -MD -MP -MF src/.deps/sipp_unittest-actions.Tpo -c -o src/sipp_unittest-actions.o `test -f 'src/actions.cpp' || echo './'`src/actions.cpp
src/actions.cpp:748:25: error: gtest/gtest.h: No such file or directory
src/actions.cpp:750: error: expected constructor, destructor, or type conversion before â(â token
src/actions.cpp:775: error: expected constructor, destructor, or type conversion before â(â token
make: *** [src/sipp_unittest-actions.o] Error 1

**Comment by rkday** [comment]
Does `make sipp

**Comment by aneeshk25** [comment]
Thanks. 
Yes, 'make sipp' worked. It means without unit test right? 
May I know what is it doing with 'git' ?
