### ISSUE TITLE
set realm on tha authorization header

### ISSUE THREAD

**Issue by davidcsi** [SIPp/sipp#733]
Hello,

Is there any way of setting the realm on the authorization header?

Thanks!

**Comment by davidcsi** [comment]
anyone?

**Comment by orgads** [comment]
It should be supported. What did you try?

**Comment by davidcsi** [comment]
thanks! there's no command-line switch to set it, is there any other way? i tried setting it in the authorization header but that didn't do anything

**Comment by orgads** [comment]
It is read from the authorization header. Can you paste/attach the script that doesn't work, and what you expect?

**Comment by davidcsi** [comment]
Thanks! Will return with actual examples, but i set it as 
```
[authentication realm=myrealm.com]
```
in the actua. xml.

whereas the destination host was something like
```
sip.myreal.me
```
i never saw the realm being set

**Comment by davidcsi** [comment]
Thanks!
I added it on the XML but that wasn't workin. Adding it on the csv file did work!
