### ISSUE TITLE
[coredump]  when i run sipp as uac, sipp core dump everytime。

### ISSUE THREAD

**Issue by gao114882** [SIPp/sipp#743]
here is my scenarios 
[register.txt](https://github.com/user-attachments/files/16721171/register.txt)

run cmd: ./sipp -r 10 -i 172.16.4.113 -p 5667  -sf register.xml -inf $csvfile 172.16.4.111:5161 -l 50 -m 200 -aa -trace_err -error_file ./reg_error.log

sipp is build by master branch,   x86_64, Centos 7.9 system.
gdb bt:
```
Core was generated by `./sipp -r 10 -i 172.16.4.113 -p 5667 -sf register.xml -inf register.csv 172.16.'.
Program terminated with signal 11, Segmentation fault.
#0  0x000000000045296d in rtpstream_playback_thread(void*) ()
(gdb) bt
#0  0x000000000045296d in rtpstream_playback_thread(void*) ()
#1  0x0000000000864ad8 in start ()
#2  0x0000000000865f50 in __clone ()
Backtrace stopped: frame did not save the PC
(gdb) 
```

**Comment by orgads** [comment]
Can you still reproduce with latest master? If it still reproduces, please attach also the wav file, a sample csv file, and if possible, a script that mocks the other end.

**Comment by gao114882** [comment]
sorry, reply so late,  still core dump.  my situation is that : uac -----> opensips----->uas。 register and invite。

```
git log 
commit d677f54fe11ba7810fdb7fece7dd317facd4067f (HEAD -> master, origin/master, origin/HEAD)
Author: Jean-Christophe Grondin <jcgrondin@genetec.com>
Date:   Wed Sep 11 13:58:03 2024 -0400

    Include the SNI for SSL client

commit fdc0c97e1d8acbe4de0d89cf26dfe74bf9b413ed
Author: Orgad Shaneh <orgad.shaneh@audiocodes.com>
Date:   Wed Sep 11 20:55:06 2024 +0300

    Fix 32-bit compilation
```

build as this:
```
git submodule update --init
docker build -t sipp -f docker/Dockerfile.full --output=. --target=bin .
```
here is my uac  run cmd:
```
./sipp -r 200 -i 172.16.4.113 -p 5667  -sf register.xml -inf $register.csv 172.16.4.111:5161 -l 400 -m 1000 -aa -trace_err -error_file ./reg_error.log
```
my uas run cmd:
```
./sipp -i 172.16.4.114 -p 5660 -sf branchs.xml -trace_err -error_file ./recvError.log -min_rtp_port 10000 -max_rtp_port 14000 -aa 
```
the xml and core file in the zip files 

[sipp-core.zip](https://github.com/user-attachments/files/17000739/sipp-core.zip)

**Comment by orgads** [comment]
Thank you for the reproducer. Can you check it #755 solves it for you? Works here.

**Comment by gao114882** [comment]
it's userful,  thanks
