### ISSUE TITLE
Need version 3.7.3 Published - Require [auto_media_port]

### ISSUE THREAD

**Issue by abitrusty** [SIPp/sipp#744]
Using 3.7.2 - Need the ability to generate multiple calls with unique source media ports for load testing

Using [rtpstream_audio_port] gives this functionality but it then stops rfc2833 dtmf digits (using  <exec play_dtmf="1234"/>) from being recognised by SBC. Not sure why - might be because the dtmf is sent from media port 0 or something completely different.

As soon as I change Invite to [media_port] DTMF works perfectly but when load testing all calls come from the same media port and SBC ends up dropping all but one call

@orgads  - is it possible to get the patch to re-implement [auto_media_port] published?

Many thanks in advance

**Comment by orgads** [comment]
Done

**Comment by abitrusty** [comment]
@orgads - legend!!! Really appreciate it!!
