### ISSUE TITLE
terminal screen truncation on MAC OS X

### ISSUE THREAD

**Issue by freeplanina** [SIPp/sipp#76]
There is a known issue with SIPP on Mac OS X, which causes the screen to be truncated, unreadable, etc. Reference: http://sourceforge.net/p/sipp/mailman/sipp-users/thread/CAN5esQLTXKGPhX3pLM7p66KGwuqmL6aMy4DCD-Dzv1nyhL-WOg@mail.gmail.com/

However, the fix proposed with usleep is not a proper fix for MAC OS X.
The problem is that logger.cpp counts on line buffering to print out properly the information on the screen. Whereas maces stdout is not always line buffers.

Therefore setlinebuf(stdout) should be added in order to ensure line buffering on MAC OS X.

By adding setlinebuf(stdout); on line 231 (SIPP 3.4.0)
void print_statistics(int last)
{
    static int first = 1;
    extern int command_mode;
    extern char *command_buffer;

```
setlinebuf(stdout);
```

....

the problem is easily fixed.

Enjoy!

**Comment by mx4492** [comment]
On the Mac OS X, even after applying the aforementioned patch, the
terminal settings are screwed up after quitting `sipp`. To fix your
terminal after quitting `sipp`, type the following command (The
letters might not echo on your terminal):

        stty sane
