### ISSUE TITLE
CMake Generate step failed.  Build files cannot be regenerated correctly.

### ISSUE THREAD

**Issue by ushapjain** [SIPp/sipp#764]
cmake . -DUSE_PCAP=1
-- SCTP is disabled
-- GSL is disabled
-- Found ssl;crypto; enabling sips support
-- Checking for one of the modules 'libpcap'
-- Configuring done (0.2s)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PCAP_LIBRARY
    linked by target "sipp_unittest" in directory /home/ap.uis.abc.com/pusha0/sipp-3.7.3
    linked by target "sipp" in directory /home/ap.uis.abc.com/pusha0/sipp-3.7.3

-- Generating done (0.0s)
CMake Generate step failed.  Build files cannot be regenerated correctly.

Kindly help.

**Comment by orgads** [comment]
If you pass `-DUSE_PCAP=1` then you need to have libpcap installed. Assuming this is linux, you should install libpcap-dev package.
