### ISSUE TITLE
The SIP CANCEL request carries two "From" header fields

### ISSUE THREAD

**Issue by pengwang7** [SIPp/sipp#767]
Here is the content of my XML file. When using Wireshark to capture packets, I found that two "From" header fields were sent. Did I do something wrong?

CANCEL sip:2400000@10.22.96.125:5060 SIP/2.0
Via: SIP/2.0/UDP 192.168.64.128:5060;rport;branch=z9hG4bK-15084-1-0
Call-ID: 1-15084@192.168.64.128
From: <sip:1800000@192.168.64.128>
From: <sip:1800000@192.168.64.128:5060>;tag=150841
To: <sip:2400000@10.22.96.125:5060>;tag=97dc6e27e1f04af99ec45bbd5e09a7c4
Call-ID: 1-15084@192.168.64.128
CSeq: 1 CANCEL
Max-Forwards: 70
Content-Length: 0

```
    <!-- UAC recv the 180 Ringing for INVITE -->
    <recv response="180" crlf="true">
        <action>
	        <ereg regexp="branch=([^;]*)" search_in="msg" check_it="true" assign_to="whole_branch_ivt,branch_ivt"/>
        </action>
    </recv>

    <!-- Pauses between 1000ms and 2000ms -->
    <pause distribution="uniform" min="1000" max="2000" crlf="true"/>

    <!-- UAC send CANCEL -->
    <send>
        <![CDATA[

            CANCEL sip:[field1]@[remote_ip]:[remote_port] SIP/2.0
            Via: SIP/2.0/[transport] [local_ip]:[local_port];rport;branch=[$branch_ivt]
	    From: <sip:[field0]@[local_ip]:[local_port]>;tag=[pid][call_number]
            To: <sip:[field1]@[remote_ip]:[remote_port]>[peer_tag_param]
            Call-ID: [call_id]
            CSeq: 1 CANCEL
            Max-Forwards: 70
            Content-Length: 0

        ]]>
    </send>

    <!-- UAC recv 200 OK for the CANCEL -->
    <recv response="200" crlf="true">
    </recv>

    <!-- UAC recv 487 -->
    <recv response="487" crlf="true">
    </recv>
```

**Comment by wdoekes** [comment]
I suspect that this `<ereg regexp="branch=([^;]*)" search_in="msg" check_it="true" assign_to="whole_branch_ivt,branch_ivt"/>` copied both the branch and  the following From, up to the first double quote.
