### ISSUE TITLE
Invalid result responsibility

### ISSUE THREAD

**Issue by vit1251** [SIPp/sipp#77]
Hi,

Let's look on most popular system. Now have modern idea make modules and unit based architecture. When people want start using pcap it may be possible by command line or when some people want require write a result class respondew rithout ncurses.

I think that SIPp require more Interface way to make possible stor result to XML or another result set. Let's make possible make using from another code as part of system it require more modular architecture.

Thanx.

**Comment by wdoekes** [comment]
I suspect that English is not your native language. This doesn't help your case.

It looks like your feature request boils down to something like this:

> It'd be great if SIPp had a machine-friendly interface, both for calling it and for interpreting the results.

While that does sound great, this doesn't provide any starting point other than "improvements are an improvement". I'm closing this out for now. Feel free to reopen if you have more concrete suggestions.
