### ISSUE TITLE
Additional keywords

### ISSUE THREAD

**Issue by rkday** [SIPp/sipp#8]
SIPped, the Polycom fork of SIPp (https://github.com/SIPp/polycom-sipped) has support for new keywords - [remote_tag], [remote_tag_param], [contact_uri], [contact_value], [to_uri], [to_value], [from_uri] and [from_value]. It might be good to get this merged into the main SIPp code (although other Polycom additions like the ability to just get the value from a last_ header may replace from_value etc.).

It looks as though the relevant commits are a5011a6 (remote_tag, remote_tag_param) and 9013201 (the others).

**Comment by wdoekes** [comment]
Not really the right way to go. Better add selectors/modifiers to extract values from e.g. last_To: `last_To.param.tag` or `last_To.uri`
