### ISSUE TITLE
wrong response computation in auth header

### ISSUE THREAD

**Issue by emabo** [SIPp/sipp#87]
there is a problem in createAuthResponseMD5 (file src/auth.cpp). It seems that changeset ff340b80 added an issue when computing a response. Also the comment of the changeset seems to suggest something wrong:
"verifyAuthHeader now takes auth-int into account, but the response is now calculated wrongly"

So, I propose following change to modify the behaviour:

diff --git a/src/auth.cpp b/src/auth.cpp
index ecd1b9e..5add2c1 100644
--- a/src/auth.cpp
+++ b/src/auth.cpp
@@ -260,7 +260,6 @@ int createAuthResponseMD5(const char *user,
     unsigned char ha1_hex[HASH_HEX_SIZE+1], ha2_hex[HASH_HEX_SIZE+1];
     char tmp[MAX_HEADER_LEN];
     md5_state_t Md5Ctx;
-    const char authint[] = "auth-int";

     // Load in A1
     md5_init(&Md5Ctx);
@@ -307,7 +306,7 @@ int createAuthResponseMD5(const char *user,
         md5_append(&Md5Ctx, (md5_byte_t *) ":", 1);
         md5_append(&Md5Ctx, (md5_byte_t *) cnonce, strlen(cnonce));
         md5_append(&Md5Ctx, (md5_byte_t *) ":", 1);
-        md5_append(&Md5Ctx, (md5_byte_t *) authint, strlen(authint));
+        md5_append(&Md5Ctx, (md5_byte_t *) authtype, strlen(authtype));
     }
     md5_append(&Md5Ctx, (md5_byte_t *) ":", 1);
     md5_append(&Md5Ctx, (md5_byte_t *) &ha2_hex, HASH_HEX_SIZE);

**Comment by rkday** [comment]
Sorry - I do agree that this was a valid bug (which you'd only hit if you had `cnonce` but not `qop="auth-int"`, which is why I missed it). I've just accepted #123 which should fix it.
